const TRANSLATION_DATA = {
"pokemon": {
"アーケオス":"Archeops",
"アーケン":"Archen",
"アーゴヨン":"Naganadel",
"アーボ":"Ekans",
"アーボック":"Arbok",
"アーマーガア":"Corviknight",
"アーマルド":"Armaldo",
"アイアント":"Durant",
"アオガラス":"Corvisquire",
"アギルダー":"Accelgor",
"アクジキング":"Guzzlord",
"アグノム":"Azelf",
"アゲハント":"Beautifly",
"アゴジムシ":"Grubbin",
"アサナン":"Meditite",
"アシマリ":"Popplio",
"アシレーヌ":"Primarina",
"アズマオウ":"Seaking",
"アチゲータ":"Crocalor",
"アチャモ":"Torchic",
"アップリュー":"Flapple",
"アノクサ":"Bramblin",
"アノプス":"Anorith",
"アノホラグサ":"Brambleghast",
"アバゴーラ":"Carracosta",
"アブソル":"Absol",
"アブソル(メガ)":"Absol-Mega",
"アブリー":"Cutiefly",
"アブリボン":"Ribombee",
"アマージョ":"Tsareena",
"アマカジ":"Bounsweet",
"アママイコ":"Steenee",
"アマルス":"Amaura",
"アマルルガ":"Aurorus",
"アメタマ":"Surskit",
"アメモース":"Masquerain",
"アヤシシ":"Wyrdeer",
"アラブルタケ":"Brute Bonnet",
"アリアドス":"Ariados",
"アリゲイツ":"Croconaw",
"アルクジラ":"Cetoddle",
"アルセウス":"Arceus",
"アルセウス(悪)":"Arceus-Dark",
"アルセウス(炎)":"Arceus-Fire",
"アルセウス(格)":"Arceus-Fighting",
"アルセウス(岩)":"Arceus-Rock",
"アルセウス(鋼)":"Arceus-Steel",
"アルセウス(水)":"Arceus-Water",
"アルセウス(草)":"Arceus-Grass",
"アルセウス(地)":"Arceus-Ground",
"アルセウス(虫)":"Arceus-Bug",
"アルセウス(超)":"Arceus-Psychic",
"アルセウス(電)":"Arceus-Electric",
"アルセウス(毒)":"Arceus-Poison",
"アルセウス(飛)":"Arceus-Flying",
"アルセウス(氷)":"Arceus-Ice",
"アルセウス(妖)":"Arceus-Fairy",
"アルセウス(竜)":"Arceus-Dragon",
"アルセウス(霊)":"Arceus-Ghost",
"アンノーン":"Unown",
"イイネイヌ":"Okidogi",
"イーブイ":"Eevee",
"イーユイ":"Chi-Yu",
"イエッサン(♀)":"Indeedee-F",
"イエッサン(♂)":"Indeedee",
"イオルブ":"Orbeetle",
"イキリンコ":"Squawkabilly",
"イシズマイ":"Dwebble",
"イシツブテ":"Geodude",
"イシツブテ(アローラ)":"Geodude-Alola",
"イシヘンジン":"Stonjourner",
"イダイトウ(♀)":"Basculegion-F",
"イダイトウ(♂)":"Basculegion",
"イダイナキバ":"Great Tusk",
"イッカネズミ":"Maushold",
"イトマル":"Spinarak",
"イノムー":"Piloswine",
"イベルタル":"Yveltal",
"イルカマン":"Palafin",
"イルカマン(変身)":"Palafin-Hero",
"イルミーゼ":"Illumise",
"イワーク":"Onix",
"イワパレス":"Crustle",
"イワンコ":"Rockruff",
"インテレオン":"Inteleon",
"ウインディ":"Arcanine",
"ウインディ(ヒスイ)":"Arcanine-Hisui",
"ウーラオス(一撃)":"Urshifu",
"ウーラオス(連撃)":"Urshifu-Rapid-Strike",
"ウールー":"Wooloo",
"ウェーニバル":"Quaquaval",
"ウェルカモ":"Quaxwell",
"ウォーグル":"Braviary",
"ウォーグル(ヒスイ)":"Braviary-Hisui",
"ウオチルドン":"Arctovish",
"ウオノラゴン":"Dracovish",
"ウガツホムラ":"Gouging Fire",
"ウソッキー":"Sudowoodo",
"ウソハチ":"Bonsly",
"ウッウ":"Cramorant",
"ウツドン":"Weepinbell",
"ウツボット":"Victreebel",
"ウツロイド":"Nihilego",
"ウデッポウ":"Clauncher",
"ウネルミナモ":"Walking Wake",
"ウパー":"Wooper",
"ウパー(パルデア)":"Wooper-Paldea",
"ウミディグダ":"Wiglett",
"ウミトリオ":"Wugtrio",
"ウリムー":"Swinub",
"ウルガモス":"Volcarona",
"エアームド":"Skarmory",
"エイパム":"Aipom",
"エースバーン":"Cinderace",
"エーフィ":"Espeon",
"エクスレッグ":"Lokix",
"エテボース":"Ambipom",
"エネコ":"Skitty",
"エネコロロ":"Delcatty",
"エビワラー":"Hitmonchan",
"エムリット":"Mesprit",
"エモンガ":"Emolga",
"エリキテル":"Helioptile",
"エルフーン":"Whimsicott",
"エルレイド":"Gallade",
"エルレイド(メガ)":"Gallade-Mega",
"エレキッド":"Elekid",
"エレキブル":"Electivire",
"エレザード":"Heliolisk",
"エレズン":"Toxel",
"エレブー":"Electabuzz",
"エンテイ":"Entei",
"エンニュート":"Salazzle",
"エンブオー":"Emboar",
"エンペルト":"Empoleon",
"オーガポン":"Ogerpon",
"オーガポン(炎)":"Ogerpon-Hearthflame",
"オーガポン(岩)":"Ogerpon-Cornerstone",
"オーガポン(水)":"Ogerpon-Wellspring",
"オオスバメ":"Swellow",
"オーダイル":"Feraligatr",
"オオタチ":"Furret",
"オオニューラ":"Sneasler",
"オーベム":"Beheeyem",
"オーロット":"Trevenant",
"オーロンゲ":"Grimmsnarl",
"オクタン":"Octillery",
"オコリザル":"Primeape",
"オシャマリ":"Brionne",
"オタチ":"Sentret",
"オタマロ":"Tympole",
"オドシシ":"Stantler",
"オトシドリ":"Bombirdier",
"オトスパス":"Grapploct",
"オドリドリ(炎)":"Oricorio",
"オドリドリ(超)":"Oricorio-Pa'u",
"オドリドリ(電)":"Oricorio-Pom-Pom",
"オドリドリ(霊)":"Oricorio-Sensu",
"オニゴーリ":"Glalie",
"オニゴーリ(メガ)":"Glalie-Mega",
"オニシズクモ":"Araquanid",
"オニスズメ":"Spearow",
"オニドリル":"Fearow",
"オノノクス":"Haxorus",
"オノンド":"Fraxure",
"オムスター":"Omastar",
"オムナイト":"Omanyte",
"オラチフ":"Maschiff",
"オリーヴァ":"Arboliva",
"オリーニョ":"Dolliv",
"オンバーン":"Noivern",
"オンバット":"Noibat",
"ガーディ":"Growlithe",
"ガーディ(ヒスイ)":"Growlithe-Hisui",
"ガーメイル":"Mothim",
"カイオーガ":"Kyogre",
"カイオーガ(ゲンシ)":"Kyogre-Primal",
"カイデン":"Wattrel",
"カイリキー":"Machamp",
"カイリュー":"Dragonite",
"カイロス":"Pinsir",
"カイロス(メガ)":"Pinsir-Mega",
"カエンジシ":"Pyroar",
"ガオガエン":"Incineroar",
"カクレオン":"Kecleon",
"ガケガニ":"Klawf",
"カゲボウズ":"Shuppet",
"カジッチュ":"Applin",
"カジリガメ":"Drednaw",
"ガチグマ":"Ursaluna",
"ガチグマ(赫月)":"Ursaluna-Bloodmoon",
"カチコール":"Bergmite",
"ガチゴラス":"Tyrantrum",
"カヌチャン":"Tinkatink",
"ガバイト":"Gabite",
"カバルドン":"Hippowdon",
"カビゴン":"Snorlax",
"カプ・コケコ":"Tapu Koko",
"カプ・テテフ":"Tapu Lele",
"カプ・ブルル":"Tapu Bulu",
"カプ・レヒレ":"Tapu Fini",
"カプサイジ":"Capsakid",
"カブト":"Kabuto",
"カブトプス":"Kabutops",
"ガブリアス":"Garchomp",
"ガブリアス(メガ)":"Garchomp-Mega",
"カブルモ":"Karrablast",
"カポエラー":"Hitmontop",
"ガマガル":"Palpitoad",
"ガマゲロゲ":"Seismitoad",
"カマスジョー":"Barraskewda",
"カミツオロチ":"Hydrapple",
"カミッチュ":"Dipplin",
"カミツルギ":"Kartana",
"カムカメ":"Chewtle",
"カメール":"Wartortle",
"カメックス":"Blastoise",
"カメックス(メガ)":"Blastoise-Mega",
"カメテテ":"Binacle",
"ガメノデス":"Barbaracle",
"カモネギ":"Farfetch'd",
"カモネギ(ガラル)":"Farfetch'd-Galar",
"カラカラ":"Cubone",
"ガラガラ":"Marowak",
"ガラガラ(アローラ)":"Marowak-Alola",
"カラサリス":"Silcoon",
"カラナクシ":"Shellos",
"カラマネロ":"Malamar",
"カラミンゴ":"Flamigo",
"カリキリ":"Fomantis",
"ガルーラ":"Kangaskhan",
"ガルーラ(メガ)":"Kangaskhan-Mega",
"カルボウ":"Charcadet",
"ガントル":"Boldore",
"ギアル":"Klink",
"ギガイアス":"Gigalith",
"ギギアル":"Klang",
"ギギギアル":"Klinklang",
"キチキギス":"Fezandipiti",
"キテルグマ":"Bewear",
"キノガッサ":"Breloom",
"キノココ":"Shroomish",
"キバゴ":"Axew",
"キバニア":"Carvanha",
"キマワリ":"Sunflora",
"ギモー":"Morgrem",
"キモリ":"Treecko",
"キャタピー":"Caterpie",
"キャモメ":"Wingull",
"ギャラドス":"Gyarados",
"ギャラドス(メガ)":"Gyarados-Mega",
"ギャロップ":"Rapidash",
"ギャロップ(ガラル)":"Rapidash-Galar",
"キュウコン":"Ninetales",
"キュウコン(アローラ)":"Ninetales-Alola",
"キュレム":"Kyurem",
"キュレム(ブラック)":"Kyurem-Black",
"キュレム(ホワイト)":"Kyurem-White",
"キュワワー":"Comfey",
"キョジオーン":"Garganacl",
"キラーメ":"Glimmet",
"ギラティナ(アナザー)":"Giratina",
"ギラティナ(オリジン)":"Giratina-Origin",
"キラフロル":"Glimmora",
"キリキザン":"Bisharp",
"キリンリキ":"Girafarig",
"ギルガルド(剣)":"Aegislash-Blade",
"ギルガルド(盾)":"Aegislash",
"キルリア":"Kirlia",
"キレイハナ":"Bellossom",
"キングドラ":"Kingdra",
"キングラー":"Kingler",
"クイタラン":"Heatmor",
"クエスパトラ":"Espathra",
"クサイハナ":"Gloom",
"クスネ":"Nickit",
"クズモー":"Skrelp",
"グソクムシャ":"Golisopod",
"クチート":"Mawile",
"クチート(メガ)":"Mawile-Mega",
"クヌギダマ":"Pineco",
"クマシュン":"Cubchoo",
"グラードン":"Groudon",
"グラードン(ゲンシ)":"Groudon-Primal",
"グライオン":"Gliscor",
"グライガー":"Gligar",
"グラエナ":"Mightyena",
"クラブ":"Krabby",
"グランブル":"Granbull",
"クリムガン":"Druddigon",
"グルトン":"Lechonk",
"クルマユ":"Swadloon",
"クルミル":"Sewaddle",
"グレイシア":"Glaceon",
"クレセリア":"Cresselia",
"グレッグル":"Croagunk",
"クレッフィ":"Klefki",
"クレベース":"Avalugg",
"クレベース(ヒスイ)":"Avalugg-Hisui",
"グレンアルマ":"Armarouge",
"クロバット":"Crobat",
"クワガノン":"Vikavolt",
"クワッス":"Quaxly",
"ケイコウオ":"Finneon",
"ケーシィ":"Abra",
"ケケンカニ":"Crabominable",
"ゲコガシラ":"Frogadier",
"ケッキング":"Slaking",
"ゲッコウガ":"Greninja",
"ゲッコウガ(サトシ)":"Greninja-Bond",
"ゲノセクト":"Genesect",
"ケムッソ":"Wurmple",
"ケララッパ":"Trumbeak",
"ケルディオ":"Keldeo",
"ケロマツ":"Froakie",
"ゲンガー":"Gengar",
"ゲンガー(メガ)":"Gengar-Mega",
"ケンタロス":"Tauros",
"ケンタロス(パルデア炎)":"Tauros-Paldea-Blaze",
"ケンタロス(パルデア水)":"Tauros-Paldea-Aqua",
"ケンタロス(パルデア闘)":"Tauros-Paldea-Combat",
"ケンホロウ":"Unfezant",
"コアルヒー":"Ducklett",
"コイキング":"Magikarp",
"コイル":"Magnemite",
"ゴウカザル":"Infernape",
"ゴーゴート":"Gogoat",
"ゴース":"Gastly",
"コータス":"Torkoal",
"ゴーリキー":"Machoke",
"コオリッポ(アイス)":"Eiscue",
"コオリッポ(ナイス)":"Eiscue-Noice",
"コクーン":"Kakuna",
"ゴクリン":"Gulpin",
"ココガラ":"Rookidee",
"ココドラ":"Aron",
"ココロモリ":"Swoobat",
"コジオ":"Nacli",
"コジョフー":"Mienfoo",
"コジョンド":"Mienshao",
"コスモウム":"Cosmoem",
"コスモッグ":"Cosmog",
"コソクムシ":"Wimpod",
"コダック":"Psyduck",
"ゴチミル":"Gothorita",
"ゴチム":"Gothita",
"ゴチルゼル":"Gothitelle",
"コドラ":"Lairon",
"ゴニョニョ":"Whismur",
"コノハナ":"Nuzleaf",
"コノヨザル":"Annihilape",
"コバルオン":"Cobalion",
"ゴビット":"Golett",
"コフーライ":"Spewpa",
"コフキムシ":"Scatterbug",
"ゴマゾウ":"Phanpy",
"コマタナ":"Pawniard",
"コモルー":"Shelgon",
"コライドン":"Koraidon",
"コラッタ":"Rattata",
"コラッタ(アローラ)":"Rattata-Alola",
"ゴリランダー":"Rillaboom",
"コリンク":"Shinx",
"ゴルーグ":"Golurk",
"ゴルダック":"Golduck",
"ゴルバット":"Golbat",
"コレクレー(徒歩)":"Gimmighoul-Roaming",
"コレクレー(箱)":"Gimmighoul",
"ゴローニャ":"Golem",
"ゴローニャ(アローラ)":"Golem-Alola",
"ゴローン":"Graveler",
"ゴローン(アローラ)":"Graveler-Alola",
"コロトック":"Kricketune",
"コロボーシ":"Kricketot",
"コロモリ":"Woobat",
"ゴロンダ":"Pangoro",
"コンパン":"Venonat",
"ゴンベ":"Munchlax",
"サーナイト":"Gardevoir",
"サーナイト(メガ)":"Gardevoir-Mega",
"サーフゴー":"Gholdengo",
"サイドン":"Rhydon",
"サイホーン":"Rhyhorn",
"サクラビス":"Gorebyss",
"サケブシッポ":"Scream Tail",
"サザンドラ":"Hydreigon",
"ザシアン(剣の王)":"Zacian",
"ザシアン(勇者)":"Zacian",
"サシカマス":"Arrokuda",
"サダイジャ":"Sandaconda",
"サッチムシ":"Blipbug",
"サナギラス":"Pupitar",
"サニーゴ":"Corsola",
"サニーゴ(ガラル)":"Corsola-Galar",
"サニゴーン":"Cursola",
"サボネア":"Cacnea",
"ザマゼンタ(盾の王)":"Zamazenta",
"ザマゼンタ(勇者)":"Zamazenta",
"サマヨール":"Dusclops",
"サメハダー":"Sharpedo",
"サメハダー(メガ)":"Sharpedo-Mega",
"ザルード":"Zarude",
"サルノリ":"Grookey",
"サワムラー":"Hitmonlee",
"ザングース":"Zangoose",
"サンダー":"Zapdos",
"サンダー(ガラル)":"Zapdos-Galar",
"サンダース":"Jolteon",
"サンド":"Sandshrew",
"サンド(アローラ)":"Sandshrew-Alola",
"サンドパン":"Sandslash",
"サンドパン(アローラ)":"Sandslash-Alola",
"シードラ":"Seadra",
"ジーランス":"Relicanth",
"シェイミ(スカイ)":"Shaymin-Sky",
"シェイミL":"Shaymin",
"シェルダー":"Shellder",
"ジオヅム":"Naclstack",
"ジガルデ(10%)":"Zygarde-10%",
"ジガルデ(100%)":"Zygarde-Complete",
"ジガルデ(50%)":"Zygarde",
"シガロコ":"Rellor",
"シキジカ":"Deerling",
"ジグザグマ":"Zigzagoon",
"ジグザグマ(ガラル)":"Zigzagoon-Galar",
"シザリガー":"Crawdaunt",
"ジジーロン":"Drampa",
"シシコ":"Litleo",
"シズクモ":"Dewpider",
"ジバコイル":"Magnezone",
"シビシラス":"Tynamo",
"シビビール":"Eelektrik",
"シビルドン":"Eelektross",
"ジヘッド":"Zweilous",
"シママ":"Blitzle",
"ジメレオン":"Drizzile",
"ジャノビー":"Servine",
"ジャラコ":"Jangmo-o",
"ジャラランガ":"Kommo-o",
"ジャランゴ":"Hakamo-o",
"シャリタツ":"Tatsugiri",
"ジャローダ":"Serperior",
"シャワーズ":"Vaporeon",
"シャンデラ":"Chandelure",
"ジュカイン":"Sceptile",
"ジュカイン(メガ)":"Sceptile-Mega",
"ジュゴン":"Dewgong",
"シュシュプ":"Spritzee",
"ジュナイパー":"Decidueye",
"ジュナイパー(ヒスイ)":"Decidueye-Hisui",
"シュバルゴ":"Escavalier",
"ジュプトル":"Grovyle",
"ジュペッタ":"Banette",
"ジュペッタ(メガ)":"Banette-Mega",
"ジュラルドン":"Duraludon",
"ジラーチ":"Jirachi",
"シルヴァディ":"Silvally",
"シルシュルー":"Shroodle",
"シロデスナ":"Palossand",
"シンボラー":"Sigilyph",
"スイクン":"Suicune",
"ズガイドス":"Cranidos",
"スカタンク":"Skuntank",
"ズガドーン":"Blacephalon",
"スカンプー":"Stunky",
"スコヴィラン":"Scovillain",
"スコルピ":"Skorupi",
"スターミー":"Starmie",
"ストライク":"Scyther",
"ストリンダー(ハイ)":"Toxtricity",
"ストリンダー(ロー)":"Toxtricity-Low-Key",
"スナノケガワ":"Sandy Shocks",
"スナバァ":"Sandygast",
"スナヘビ":"Silicobra",
"ズバット":"Zubat",
"スバメ":"Taillow",
"スピアー":"Beedrill",
"スピアー(メガ)":"Beedrill-Mega",
"ズピカ":"Tadbulb",
"スボミー":"Budew",
"スリーパー":"Hypno",
"スリープ":"Drowzee",
"ズルズキン":"Scrafty",
"ズルッグ":"Scraggy",
"スワンナ":"Swanna",
"セキタンザン":"Coalossal",
"セグレイブ":"Baxcalibur",
"ゼクロム":"Zekrom",
"セゴール":"Arctibax",
"ゼニガメ":"Squirtle",
"セビエ":"Frigibax",
"ゼブライカ":"Zebstrika",
"ゼラオラ":"Zeraora",
"ゼルネアス":"Xerneas",
"セレビィ":"Celebi",
"ゾウドウ":"Cufant",
"ソウブレイズ":"Ceruledge",
"ソーナノ":"Wynaut",
"ソーナンス":"Wobbuffet",
"ソルガレオ":"Solgaleo",
"ソルロック":"Solrock",
"ゾロア":"Zorua",
"ゾロア(ヒスイ)":"Zorua-Hisui",
"ゾロアーク":"Zoroark",
"ゾロアーク(ヒスイ)":"Zoroark-Hisui",
"ダークライ":"Darkrai",
"ダーテング":"Shiftry",
"ダイオウドウ":"Copperajah",
"タイカイデン":"Kilowattrel",
"ダイケンキ":"Samurott",
"ダイケンキ(ヒスイ)":"Samurott-Hisui",
"ダイノーズ":"Probopass",
"タイプ：ヌル":"Type: Null",
"タイレーツ":"Falinks",
"タギングル":"Grafaiai",
"ダグトリオ":"Dugtrio",
"ダグトリオ(アローラ)":"Dugtrio-Alola",
"ダクマ":"Kubfu",
"ダゲキ":"Sawk",
"タケルライコ":"Raging Bolt",
"ダストダス":"Garbodor",
"タタッコ":"Clobbopus",
"ダダリン":"Dhelmise",
"タチフサグマ":"Obstagoon",
"タッツー":"Horsea",
"タツベイ":"Bagon",
"タテトプス":"Shieldon",
"タネボー":"Seedot",
"ダブラン":"Duosion",
"タブンネ":"Audino",
"タブンネ(メガ)":"Audino-Mega",
"タマゲタケ":"Foongus",
"タマザラシ":"Spheal",
"タマタマ":"Exeggcute",
"タマンタ":"Mantyke",
"タマンチュラ":"Tarountula",
"タルップル":"Appletun",
"ダルマッカ":"Darumaka",
"ダルマッカ(ガラル)":"Darumaka-Galar",
"ダンゴロ":"Roggenrola",
"タンドン":"Rolycoly",
"ダンバル":"Beldum",
"チェリム":"Cherrim",
"チェリンボ":"Cherubi",
"チオンジェン":"Wo-Chien",
"チゴラス":"Tyrunt",
"チコリータ":"Chikorita",
"チャーレム":"Medicham",
"チャーレム(メガ)":"Medicham-Mega",
"チャオブー":"Pignite",
"チャデス":"Poltchageist",
"チュリネ":"Petilil",
"チョボマキ":"Shelmet",
"チョロネコ":"Purrloin",
"チョンチー":"Chinchou",
"チラーミィ":"Minccino",
"チラチーノ":"Cinccino",
"チリーン":"Chimecho",
"チルタリス":"Altaria",
"チルタリス(メガ)":"Altaria-Mega",
"チルット":"Swablu",
"チヲハウハネ":"Slither Wing",
"ツタージャ":"Snivy",
"ツチニン":"Nincada",
"ツツケラ":"Pikipek",
"ツボツボ":"Shuckle",
"ツンデツンデ":"Stakataka",
"ツンベアー":"Beartic",
"ディアルガ":"Dialga",
"ディアルガ(オリジン)":"Dialga-Origin",
"ディアンシー":"Diancie",
"ディアンシー(メガ)":"Diancie-Mega",
"ディグダ":"Diglett",
"ディグダ(アローラ)":"Diglett-Alola",
"ディンルー":"Ting-Lu",
"テールナー":"Braixen",
"デオキシス(アタック)":"Deoxys-Attack",
"デオキシス(スピード)":"Deoxys-Speed",
"デオキシス(ディフェンス)":"Deoxys-Defense",
"デオキシス(ノーマル)":"Deoxys",
"デカグース":"Gumshoos",
"デカヌチャン":"Tinkaton",
"デスカーン":"Cofagrigus",
"デスバーン":"Runerigus",
"デスマス":"Yamask",
"デスマス(ガラル)":"Yamask-Galar",
"テッカグヤ":"Celesteela",
"テッカニン":"Ninjask",
"テッシード":"Ferroseed",
"テツノイサハ":"Iron Leaves",
"テツノイバラ":"Iron Thorns",
"テツノイワオ":"Iron Boulder",
"テツノカイナ":"Iron Hands",
"テツノカシラ":"Iron Crown",
"テツノコウベ":"Iron Jugulis",
"テツノツツミ":"Iron Bundle",
"テツノドクガ":"Iron Moth",
"テツノブジン":"Iron Valiant",
"テツノワダチ":"Iron Treads",
"テッポウオ":"Remoraid",
"デデンネ":"Dedenne",
"テブリム":"Hattrem",
"テラキオン":"Terrakion",
"テラパゴス(ステラ)":"Terapagos",
"テラパゴス(テラスタル)":"Terapagos",
"テラパゴス(ノーマル)":"Terapagos",
"デリバード":"Delibird",
"デルビル":"Houndour",
"デンジュモク":"Xurkitree",
"デンヂムシ":"Charjabug",
"デンチュラ":"Galvantula",
"デンリュウ":"Ampharos",
"デンリュウ(メガ)":"Ampharos-Mega",
"ドオー":"Clodsire",
"ドータクン":"Bronzong",
"ドードー":"Doduo",
"ドードリオ":"Dodrio",
"ドーブル":"Smeargle",
"ドーミラー":"Bronzor",
"ドガース":"Koffing",
"ドククラゲ":"Tentacruel",
"ドクケイル":"Dustox",
"ドクロッグ":"Toxicroak",
"トゲキッス":"Togekiss",
"トゲチック":"Togetic",
"トゲデマル":"Togedemaru",
"トゲピー":"Togepi",
"ドゴーム":"Loudred",
"ドサイドン":"Rhyperior",
"トサキント":"Goldeen",
"ドジョッチ":"Barboach",
"ドダイトス":"Torterra",
"ドッコラー":"Timburr",
"ドデカバシ":"Toucannon",
"ドテッコツ":"Gurdurr",
"トドグラー":"Sealeo",
"ドドゲザン":"Kingambit",
"トドゼルガ":"Walrein",
"トドロクツキ":"Roaring Moon",
"ドヒドイデ":"Toxapex",
"ドラパルト":"Dragapult",
"ドラピオン":"Drapion",
"ドラミドロ":"Dragalge",
"ドラメシヤ":"Dreepy",
"トランセル":"Metapod",
"トリデプス":"Bastiodon",
"トリトドン":"Gastrodon",
"トリミアン":"Furfrou",
"ドリュウズ":"Excadrill",
"トルネロス(化身)":"Tornadus",
"トルネロス(霊獣)":"Tornadus-Therian",
"ドレディア":"Lilligant",
"ドレディア(ヒスイ)":"Lilligant-Hisui",
"トロッゴン":"Carkol",
"ドロバンコ":"Mudbray",
"トロピウス":"Tropius",
"ドロンチ":"Drakloak",
"ドンカラス":"Honchkrow",
"ドンファン":"Donphan",
"ドンメル":"Numel",
"ナエトル":"Turtwig",
"ナカヌチャン":"Tinkatuff",
"ナゲキ":"Throh",
"ナゲツケサル":"Passimian",
"ナゾノクサ":"Oddish",
"ナックラー":"Trapinch",
"ナッシー":"Exeggutor",
"ナッシー(アローラ)":"Exeggutor-Alola",
"ナットレイ":"Ferrothorn",
"ナマケロ":"Slakoth",
"ナマコブシ":"Pyukumuku",
"ナマズン":"Whiscash",
"ナミイルカ":"Finizen",
"ニダンギル":"Doublade",
"ニドキング":"Nidoking",
"ニドクイン":"Nidoqueen",
"ニドラン♀":"Nidoran-F",
"ニドラン♂":"Nidoran-M",
"ニドリーナ":"Nidorina",
"ニドリーノ":"Nidorino",
"ニャース":"Meowth",
"ニャース(アローラ)":"Meowth-Alola",
"ニャース(ガラル)":"Meowth-Galar",
"ニャイキング":"Perrserker",
"ニャオニクス(♀)":"Meowstic-F",
"ニャオニクス(♂)":"Meowstic-M",
"ニャオハ":"Sprigatito",
"ニャスパー":"Espurr",
"ニャビー":"Litten",
"ニャヒート":"Torracat",
"ニャルマー":"Glameow",
"ニャローテ":"Floragato",
"ニューラ":"Sneasel",
"ニューラ(ヒスイ)":"Sneasel-Hisui",
"ニョロゾ":"Poliwhirl",
"ニョロトノ":"Politoed",
"ニョロボン":"Poliwrath",
"ニョロモ":"Poliwag",
"ニンフィア":"Sylveon",
"ヌイコグマ":"Stufful",
"ヌオー":"Quagsire",
"ヌケニン":"Shedinja",
"ヌマクロー":"Marshtomp",
"ヌメイル":"Sliggoo",
"ヌメイル(ヒスイ)":"Sliggoo-Hisui",
"ヌメラ":"Goomy",
"ヌメルゴン":"Goodra",
"ヌメルゴン(ヒスイ)":"Goodra-Hisui",
"ネイティ":"Natu",
"ネイティオ":"Xatu",
"ネオラント":"Lumineon",
"ネギガナイト":"Sirfetch'd",
"ネクロズマ":"Necrozma",
"ネクロズマ(ウルトラ)":"Necrozma",
"ネクロズマ(月食)":"Necrozma-Dawn Wings",
"ネクロズマ(日食)":"Necrozma-Dusk Mane",
"ネッコアラ":"Komala",
"ネマシュ":"Morelull",
"ネンドール":"Claydol",
"ノクタス":"Cacturne",
"ノココッチ":"Dudunsparce",
"ノコッチ":"Dunsparce",
"ノズパス":"Nosepass",
"ノノクラゲ":"Toedscool",
"ハーデリア":"Herdier",
"パーモット":"Pawmot",
"パールル":"Clamperl",
"バイウールー":"Dubwool",
"バイバニラ":"Vanilluxe",
"バウッツェル":"Dachsbun",
"パウワウ":"Seel",
"パオジアン":"Chien-Pao",
"バオッキー":"Simisear",
"バオップ":"Pansear",
"ハカドッグ":"Houndstone",
"ハガネール":"Steelix",
"ハガネール(メガ)":"Steelix-Mega",
"ハギギシリ":"Bruxish",
"バクーダ":"Camerupt",
"バクーダ(メガ)":"Camerupt-Mega",
"バクオング":"Exploud",
"バクガメス":"Turtonator",
"バクフーン":"Typhlosion",
"バクフーン(ヒスイ)":"Typhlosion-Hisui",
"ハクリュー":"Dragonair",
"バケッチャ":"Pumpkaboo",
"バケッチャ(小)":"Pumpkaboo-Small",
"バケッチャ(大)":"Pumpkaboo-Large",
"バケッチャ(特大)":"Pumpkaboo-Super",
"バサギリ":"Kleavor",
"バシャーモ":"Blaziken",
"バシャーモ(メガ)":"Blaziken-Mega",
"ハスブレロ":"Lombre",
"ハスボー":"Lotad",
"バスラオ(青筋)":"Basculin-Blue-Striped",
"バスラオ(赤筋)":"Basculin",
"バスラオ(白筋)":"Basculin-White-Striped",
"バタフリー":"Butterfree",
"バチュル":"Joltik",
"パチリス":"Pachirisu",
"バチンウニ":"Pincurchin",
"バチンキー":"Thwackey",
"ハッサム":"Scizor",
"ハッサム(メガ)":"Scizor-Mega",
"パッチール":"Spinda",
"パッチラゴン":"Dracozolt",
"パッチルドン":"Arctozolt",
"バッフロン":"Bouffalant",
"ハトーボー":"Tranquill",
"バドレックス":"Calyrex",
"バドレックス(黒馬)":"Calyrex-Shadow",
"バドレックス(白馬)":"Calyrex-Ice",
"バニプッチ":"Vanillite",
"バニリッチ":"Vanillish",
"ハネッコ":"Hoppip",
"バネブー":"Spoink",
"ハハコモリ":"Leavanny",
"ハバタクカミ":"Flutter Mane",
"ハピナス":"Blissey",
"パピモッチ":"Fidough",
"ハブネーク":"Seviper",
"パフュートン(♀)":"Oinkologne-F",
"パフュートン(♂)":"Oinkologne",
"パモ":"Pawmi",
"パモット":"Pawmo",
"ハヤシガメ":"Grotle",
"パラス":"Paras",
"パラセクト":"Parasect",
"ハラバリー":"Bellibolt",
"ハリーセン":"Qwilfish",
"ハリーセン(ヒスイ)":"Qwilfish-Hisui",
"ハリーマン":"Overqwil",
"バリコオル":"Mr. Rime",
"ハリテヤマ":"Hariyama",
"ハリボーグ":"Quilladin",
"ハリマロン":"Chespin",
"バリヤード":"Mr. Mime",
"バリヤード(ガラル)":"Mr. Mime-Galar",
"パルキア":"Palkia",
"パルキア(オリジン)":"Palkia-Origin",
"バルキー":"Tyrogue",
"ハルクジラ":"Cetitan",
"バルジーナ":"Mandibuzz",
"パルシェン":"Cloyster",
"パルスワン":"Boltund",
"バルチャイ":"Vullaby",
"バルビート":"Volbeat",
"バンギラス":"Tyranitar",
"バンギラス(メガ)":"Tyranitar-Mega",
"ハンテール":"Huntail",
"バンバドロ":"Mudsdale",
"パンプジン":"Gourgeist",
"パンプジン(小)":"Gourgeist-Small",
"パンプジン(大)":"Gourgeist-Large",
"パンプジン(特大)":"Gourgeist-Super",
"ピィ":"Cleffa",
"ビークイン":"Vespiquen",
"ビーダル":"Bibarel",
"ヒードラン":"Heatran",
"ビードル":"Weedle",
"ピカチュウ":"Pikachu",
"ピクシー":"Clefable",
"ビクティニ":"Victini",
"ヒコザル":"Chimchar",
"ピジョット":"Pidgeot",
"ピジョット(メガ)":"Pidgeot-Mega",
"ピジョン":"Pidgeotto",
"ピチュー":"Pichu",
"ビッパ":"Bidoof",
"ピッピ":"Clefairy",
"ヒドイデ":"Mareanie",
"ヒトカゲ":"Charmander",
"ヒトツキ":"Honedge",
"ヒトデマン":"Staryu",
"ヒトモシ":"Litwick",
"ヒノアラシ":"Cyndaquil",
"ヒノヤコマ":"Fletchinder",
"ヒバニー":"Scorbunny",
"ヒヒダルマ":"Darmanitan",
"ヒヒダルマ(ガラル,ダルマ)":"Darmanitan-Galar-Zen",
"ヒヒダルマ(ガラル)":"Darmanitan-Galar",
"ヒヒダルマ(達磨)":"Darmanitan-Zen",
"ビビヨン":"Vivillon",
"ビブラーバ":"Vibrava",
"ヒポポタス":"Hippopotas",
"ヒマナッツ":"Sunkern",
"ヒメグマ":"Teddiursa",
"ヒメンカ":"Gossifleur",
"ヒヤッキー":"Simipour",
"ヒヤップ":"Panpour",
"ヒラヒナ":"Flittle",
"ビリジオン":"Virizion",
"ビリリダマ":"Voltorb",
"ビリリダマ(ヒスイ)":"Voltorb-Hisui",
"ヒンバス":"Feebas",
"ピンプク":"Happiny",
"ファイアロー":"Talonflame",
"ファイヤー":"Moltres",
"ファイヤー(ガラル)":"Moltres-Galar",
"フィオネ":"Phione",
"ブイゼル":"Buizel",
"ブースター":"Flareon",
"フーディン":"Alakazam",
"フーディン(メガ)":"Alakazam-Mega",
"フーパ(解放)":"Hoopa-Unbound",
"フーパ(戒め)":"Hoopa",
"ブーバー":"Magmar",
"ブーバーン":"Magmortar",
"ブーピッグ":"Grumpig",
"フェローチェ":"Pheromosa",
"フォクスライ":"Thievul",
"フォッコ":"Fennekin",
"フォレトス":"Forretress",
"フカマル":"Gible",
"フクスロー":"Dartrix",
"プクリン":"Wigglytuff",
"フシギソウ":"Ivysaur",
"フシギダネ":"Bulbasaur",
"フシギバナ":"Venusaur",
"フシギバナ(メガ)":"Venusaur-Mega",
"フシデ":"Venipede",
"フタチマル":"Dewott",
"プテラ":"Aerodactyl",
"プテラ(メガ)":"Aerodactyl-Mega",
"ブニャット":"Purugly",
"ブビィ":"Magby",
"ププリン":"Igglybuff",
"フラージェス":"Florges",
"フライゴン":"Flygon",
"フラエッテ":"Floette",
"プラスル":"Plusle",
"ブラッキー":"Umbreon",
"フラベベ":"Flabebe",
"フリーザー":"Articuno",
"フリーザー(ガラル)":"Articuno-Galar",
"フリージオ":"Cryogonal",
"ブリガロン":"Chesnaught",
"ブリザポス":"Glastrier",
"ブリジュラス":"Archaludon",
"ブリムオン":"Hatterene",
"プリン":"Jigglypuff",
"ブルー":"Snubbull",
"プルリル":"Frillish",
"ブルンゲル":"Jellicent",
"フレフワン":"Aromatisse",
"フローゼル":"Floatzel",
"ブロスター":"Clawitzer",
"プロトーガ":"Tirtouga",
"ブロロローム":"Revavroom",
"ブロロン":"Varoom",
"フワライド":"Drifblim",
"フワンテ":"Drifloon",
"ヘイガニ":"Corphish",
"ヘイラッシャ":"Dondozo",
"ベイリーフ":"Bayleef",
"ベトベター":"Grimer",
"ベトベター(アローラ)":"Grimer-Alola",
"ベトベトン":"Muk",
"ベトベトン(アローラ)":"Muk-Alola",
"ベベノム":"Poipole",
"ベラカス":"Rabsca",
"ヘラクロス":"Heracross",
"ヘラクロス(メガ)":"Heracross-Mega",
"ペラップ":"Chatot",
"ペリッパー":"Pelipper",
"ヘルガー":"Houndoom",
"ヘルガー(メガ)":"Houndoom-Mega",
"ペルシアン":"Persian",
"ペルシアン(アローラ)":"Persian-Alola",
"ペロッパフ":"Swirlix",
"ベロバー":"Impidimp",
"ベロベルト":"Lickilicky",
"ペロリーム":"Slurpuff",
"ベロリンガ":"Lickitung",
"ペンドラー":"Scolipede",
"ホイーガ":"Whirlipede",
"ホウオウ":"Ho-Oh",
"ホエルオー":"Wailord",
"ホエルコ":"Wailmer",
"ホーホー":"Hoothoot",
"ボーマンダ":"Salamence",
"ボーマンダ(メガ)":"Salamence-Mega",
"ポカブ":"Tepig",
"ボクレー":"Phantump",
"ホゲータ":"Fuecoco",
"ホシガリス":"Skwovet",
"ボスゴドラ":"Aggron",
"ボスゴドラ(メガ)":"Aggron-Mega",
"ボチ":"Greavard",
"ポチエナ":"Poochyena",
"ポッタイシ":"Prinplup",
"ポッチャマ":"Piplup",
"ポットデス":"Polteageist",
"ポッポ":"Pidgey",
"ポニータ":"Ponyta",
"ポニータ(ガラル)":"Ponyta-Galar",
"ポポッコ":"Skiploom",
"ポリゴン":"Porygon",
"ポリゴン２":"Porygon2",
"ポリゴンＺ":"Porygon-Z",
"ホルード":"Diggersby",
"ボルケニオン":"Volcanion",
"ボルトロス(化身)":"Thundurus",
"ボルトロス(霊獣)":"Thundurus-Therian",
"ホルビー":"Bunnelby",
"ポワルン":"Castform",
"ポワルン(炎)":"Castform-Snowy",
"ポワルン(水)":"Castform-Rainy",
"ポワルン(氷)":"Castform-Sunny",
"マーイーカ":"Inkay",
"マーシャドー":"Marshadow",
"マイナン":"Minun",
"マギアナ":"Magearna",
"マグカルゴ":"Magcargo",
"マクノシタ":"Makuhita",
"マグマッグ":"Slugma",
"マグマラシ":"Quilava",
"マケンカニ":"Crabrawler",
"マシェード":"Shiinotic",
"マシマシラ":"Munkidori",
"マスカーニャ":"Meowscarada",
"マスキッパ":"Carnivine",
"マダツボミ":"Bellsprout",
"マタドガス":"Weezing",
"マタドガス(ガラル)":"Weezing-Galar",
"マッギョ":"Stunfisk",
"マッギョ(ガラル)":"Stunfisk-Galar",
"マッシブーン":"Buzzwole",
"マッスグマ":"Linoone",
"マッスグマ(ガラル)":"Linoone-Galar",
"マナフィ":"Manaphy",
"マニューラ":"Weavile",
"マネネ":"Mime Jr.",
"マフィティフ":"Mabosstiff",
"マフォクシー":"Delphox",
"マホイップ":"Alcremie",
"マホミル":"Milcery",
"ママンボウ":"Alomomola",
"マメバッタ":"Nymble",
"マメパト":"Pidove",
"マユルド":"Cascoon",
"マラカッチ":"Maractus",
"マリル":"Marill",
"マリルリ":"Azumarill",
"マルノーム":"Swalot",
"マルマイン":"Electrode",
"マルマイン(ヒスイ)":"Electrode-Hisui",
"マルヤクデ":"Centiskorch",
"マンキー":"Mankey",
"マンタイン":"Mantine",
"マンムー":"Mamoswine",
"ミガルーサ":"Veluza",
"ミカルゲ":"Spiritomb",
"ミジュマル":"Oshawott",
"ミズゴロウ":"Mudkip",
"ミツハニー":"Combee",
"ミニーブ":"Smoliv",
"ミニリュウ":"Dratini",
"ミネズミ":"Patrat",
"ミノマダム(鋼)":"Wormadam-Trash",
"ミノマダム(草)":"Wormadam-Sandy",
"ミノマダム(地)":"Wormadam",
"ミノムッチ":"Burmy",
"ミブリム":"Hatenna",
"ミミズズ":"Orthworm",
"ミミッキュ":"Mimikyu",
"ミミロップ":"Lopunny",
"ミミロップ(メガ)":"Lopunny-Mega",
"ミミロル":"Buneary",
"ミュウ":"Mew",
"ミュウツー":"Mewtwo",
"ミュウツー(メガX)":"Mewtwo-Mega-X",
"ミュウツー(メガY)":"Mewtwo-Mega-Y",
"ミライドン":"Miraidon",
"ミルタンク":"Miltank",
"ミルホッグ":"Watchog",
"ミロカロス":"Milotic",
"ムウマ":"Misdreavus",
"ムウマージ":"Mismagius",
"ムーランド":"Stoutland",
"ムクバード":"Staravia",
"ムクホーク":"Staraptor",
"ムゲンダイナ":"Eternatus",
"ムゲンダイナ(ムゲン)":"Eternatus",
"ムシャーナ":"Musharna",
"ムチュール":"Smoochum",
"ムックル":"Starly",
"ムンナ":"Munna",
"メェークル":"Skiddo",
"メガニウム":"Meganium",
"メガヤンマ":"Yanmega",
"メグロコ":"Sandile",
"メタグロス":"Metagross",
"メタグロス(メガ)":"Metagross-Mega",
"メタモン":"Ditto",
"メタング":"Metang",
"メッソン":"Sobble",
"メテノ":"Minior-Meteor",
"メテノ(コア)":"Minior",
"メノクラゲ":"Tentacool",
"メブキジカ":"Sawsbuck",
"メラルバ":"Larvesta",
"メリープ":"Mareep",
"メルタン":"Meltan",
"メルメタル":"Melmetal",
"メレシー":"Carbink",
"メロエッタ(超)":"Meloetta",
"メロエッタ(闘)":"Meloetta-Pirouette",
"モウカザル":"Monferno",
"モグリュー":"Drilbur",
"モクロー":"Rowlet",
"モココ":"Flaaffy",
"モジャンボ":"Tangrowth",
"モスノウ":"Frosmoth",
"モトトカゲ":"Cyclizar",
"モノズ":"Deino",
"モモワロウ":"Pecharunt",
"モルフォン":"Venomoth",
"モルペコ":"Morpeko",
"モロバレル":"Amoonguss",
"モンジャラ":"Tangela",
"モンメン":"Cottonee",
"ヤクデ":"Sizzlipede",
"ヤジロン":"Baltoy",
"ヤトウモリ":"Salandit",
"ヤドキング":"Slowking",
"ヤドキング(ガラル)":"Slowking-Galar",
"ヤドラン":"Slowbro",
"ヤドラン(ガラル)":"Slowbro-Galar",
"ヤドラン(メガ)":"Slowbro-Mega",
"ヤドン":"Slowpoke",
"ヤドン(ガラル)":"Slowpoke-Galar",
"ヤナッキー":"Simisage",
"ヤナップ":"Pansage",
"ヤバソチャ":"Sinistcha",
"ヤバチャ":"Sinistea",
"ヤブクロン":"Trubbish",
"ヤミカラス":"Murkrow",
"ヤミラミ":"Sableye",
"ヤミラミ(メガ)":"Sableye-Mega",
"ヤヤコマ":"Fletchling",
"ヤルキモノ":"Vigoroth",
"ヤレユータン":"Oranguru",
"ヤングース":"Yungoos",
"ヤンチャム":"Pancham",
"ヤンヤンマ":"Yanma",
"ユキカブリ":"Snover",
"ユキノオー":"Abomasnow",
"ユキノオー(メガ)":"Abomasnow-Mega",
"ユキハミ":"Snom",
"ユキメノコ":"Froslass",
"ユキワラシ":"Snorunt",
"ユクシー":"Uxie",
"ユニラン":"Solosis",
"ユレイドル":"Cradily",
"ユンゲラー":"Kadabra",
"ヨーギラス":"Larvitar",
"ヨーテリー":"Lillipup",
"ヨクバリス":"Greedent",
"ヨノワール":"Dusknoir",
"ヨマワル":"Duskull",
"ヨルノズク":"Noctowl",
"ヨワシ(群れ)":"Wishiwashi-School",
"ヨワシ(単独)":"Wishiwashi",
"ライコウ":"Raikou",
"ライチュウ":"Raichu",
"ライチュウ(アローラ)":"Raichu-Alola",
"ライボルト":"Manectric",
"ライボルト(メガ)":"Manectric-Mega",
"ラウドボーン":"Skeledirge",
"ラグラージ":"Swampert",
"ラグラージ(メガ)":"Swampert-Mega",
"ラクライ":"Electrike",
"ラッキー":"Chansey",
"ラッタ":"Raticate",
"ラッタ(アローラ)":"Raticate-Alola",
"ラティアス":"Latias",
"ラティアス(メガ)":"Latias-Mega",
"ラティオス":"Latios",
"ラティオス(メガ)":"Latios-Mega",
"ラビフット":"Raboot",
"ラブカス":"Luvdisc",
"ラブトロス(化身)":"Enamorus",
"ラブトロス(霊獣)":"Enamorus-Therian",
"ラプラス":"Lapras",
"ラフレシア":"Vileplume",
"ラムパルド":"Rampardos",
"ラランテス":"Lurantis",
"ラルトス":"Ralts",
"ランクルス":"Reuniclus",
"ランターン":"Lanturn",
"ランドロス(化身)":"Landorus",
"ランドロス(霊獣)":"Landorus-Therian",
"ランプラー":"Lampent",
"リーシャン":"Chingling",
"リーフィア":"Leafeon",
"リオル":"Riolu",
"リキキリン":"Farigiraf",
"リククラゲ":"Toedscruel",
"リグレー":"Elgyem",
"リザード":"Charmeleon",
"リザードン":"Charizard",
"リザードン(メガX)":"Charizard-Mega-X",
"リザードン(メガY)":"Charizard-Mega-Y",
"リリーラ":"Lileep",
"リングマ":"Ursaring",
"ルージュラ":"Jynx",
"ルカリオ":"Lucario",
"ルカリオ(メガ)":"Lucario-Mega",
"ルガルガン(黄昏)":"Lycanroc-Dusk",
"ルガルガン(真昼)":"Lycanroc",
"ルガルガン(真夜中)":"Lycanroc-Midnight",
"ルギア":"Lugia",
"ルクシオ":"Luxio",
"ルチャブル":"Hawlucha",
"ルナアーラ":"Lunala",
"ルナトーン":"Lunatone",
"ルリリ":"Azurill",
"ルンパッパ":"Ludicolo",
"レアコイル":"Magneton",
"レイスポス":"Spectrier",
"レジアイス":"Regice",
"レジエレキ":"Regieleki",
"レジギガス":"Regigigas",
"レジスチル":"Registeel",
"レジドラゴ":"Regidrago",
"レシラム":"Reshiram",
"レジロック":"Regirock",
"レックウザ":"Rayquaza",
"レックウザ(メガ)":"Rayquaza-Mega",
"レディアン":"Ledian",
"レディバ":"Ledyba",
"レドームシ":"Dottler",
"レパルダス":"Liepard",
"レントラー":"Luxray",
"ローブシン":"Conkeldurr",
"ロコン":"Vulpix",
"ロコン(アローラ)":"Vulpix-Alola",
"ロズレイド":"Roserade",
"ロゼリア":"Roselia",
"ロトム":"Rotom",
"ロトム(炎)":"Rotom-Heat",
"ロトム(水)":"Rotom-Wash",
"ロトム(草)":"Rotom-Mow",
"ロトム(飛)":"Rotom-Fan",
"ロトム(氷)":"Rotom-Frost",
"ワカシャモ":"Combusken",
"ワシボン":"Rufflet",
"ワタシラガ":"Eldegoss",
"ワタッコ":"Jumpluff",
"ワッカネズミ":"Tandemaus",
"ワナイダー":"Spidops",
"ワニノコ":"Totodile",
"ワルビアル":"Krookodile",
"ワルビル":"Krokorok",
"ワンパチ":"Yamper",
"ワンリキー":"Machop",
},
"moves": {
"１０まんばりき":"High Horsepower",
"１０まんボルト":"Thunderbolt",
"３ぼんのや":"Triple Arrows",
"ＤＤラリアット":"Darkest Lariat",
"Ｇのちから":"Grav Apple",
"Ｖジェネレート":"V-create",
"アーマーキャノン":"Armor Cannon",
"アームハンマー":"Hammer Arm",
"アイアンテール":"Iron Tail",
"アイアンヘッド":"Iron Head",
"アイアンローラー":"Steel Roller",
"アイススピナー":"Ice Spinner",
"アイスハンマー":"Ice Hammer",
"アイスボール":"Ice Ball",
"あおいほのお":"Blue Flare",
"アクアカッター":"Aqua Cutter",
"アクアジェット":"Aqua Jet",
"アクアステップ":"Aqua Step",
"アクアテール":"Aqua Tail",
"アクアブレイク":"Liquidation",
"あくうせつだん":"Spacial Rend",
"アクセルブレイク":"Collision Course",
"アクセルロック":"Accelerock",
"あくのはどう":"Dark Pulse",
"あくび":"Yawn",
"あくまのキッス":"Lovely Kiss",
"あくむ":"Nightmare",
"アクロバット":"Acrobatics",
"あさのひざし":"Morning Sun",
"アシストギア":"Gear Up",
"アシストパワー":"Stored Power",
"アシッドボム":"Acid Spray",
"アストラルビット":"Astral Barrage",
"あてみなげ":"Vital Throw",
"あなをほる":"Dig",
"あばれる":"Thrash",
"アフロブレイク":"Head Charge",
"あまいかおり":"Sweet Scent",
"あまえる":"Charm",
"あまごい":"Rain Dance",
"あやしいかぜ":"Ominous Wind",
"あやしいひかり":"Confuse Ray",
"あられ":"Hail",
"アロマセラピー":"Aromatherapy",
"アロマミスト":"Aromatic Mist",
"あわ":"Bubble",
"アンカーショット":"Anchor Shot",
"アンコール":"Encore",
"あんこくきょうだ":"Wicked Blow",
"いあいぎり":"Cut",
"いえき":"Gastro Acid",
"イカサマ":"Foul Play",
"いかり":"Rage",
"いかりのこな":"Rage Powder",
"いかりのまえば":"Super Fang",
"いじげんホール":"Hyperspace Hole",
"いじげんラッシュ":"Hyperspace Fury",
"いたみわけ":"Pain Split",
"いちゃもん":"Torment",
"いっちょうあがり":"Order Up",
"いてつくしせん":"Freezing Glare",
"いとをはく":"String Shot",
"イナズマドライブ":"Electro Drift",
"いにしえのうた":"Relic Song",
"いのちがけ":"Final Gambit",
"いのちのしずく":"Life Dew",
"いばる":"Swagger",
"いびき":"Snore",
"いやしのすず":"Heal Bell",
"いやしのねがい":"Healing Wish",
"いやしのはどう":"Heal Pulse",
"いやなおと":"Screech",
"いわおとし":"Rock Throw",
"いわくだき":"Rock Smash",
"いわなだれ":"Rock Slide",
"インファイト":"Close Combat",
"ウェーブタックル":"Wave Crash",
"ウェザーボール":"Weather Ball",
"うずしお":"Whirlpool",
"うそなき":"Fake Tears",
"うたう":"Sing",
"うたかたのアリア":"Sparkling Aria",
"うちおとす":"Smack Down",
"うつしえ":"Doodle",
"ウッドハンマー":"Wood Hammer",
"ウッドホーン":"Horn Leech",
"うっぷんばらし":"Lash Out",
"うらみ":"Spite",
"うらみつらみ":"Bitter Malice",
"エアカッター":"Air Cutter",
"エアスラッシュ":"Air Slash",
"エアロブラスト":"Aeroblast",
"エコーボイス":"Echoed Voice",
"えだづき":"Branch Poke",
"エナジーボール":"Energy Ball",
"エラがみ":"Fishious Rend",
"エレキネット":"Electroweb",
"エレキフィールド":"Electric Terrain",
"エレキボール":"Electro Ball",
"エレクトロビーム":"Electro Shot",
"えんまく":"Smokescreen",
"おいうち":"Pursuit",
"おいかぜ":"Tailwind",
"おいわい":"Celebrate",
"おうふくビンタ":"Double Slap",
"オウムがえし":"Mirror Move",
"オーバードライブ":"Overdrive",
"オーバーヒート":"Overheat",
"オーラウイング":"Esper Wing",
"オーラぐるま":"Aura Wheel",
"オーロラビーム":"Aurora Beam",
"オーロラベール":"Aurora Veil",
"おかたづけ":"Tidy Up",
"おきみやげ":"Memento",
"オクタンほう":"Octazooka",
"おさきにどうぞ":"After You",
"おしおき":"Punishment",
"おしゃべり":"Chatter",
"おたけび":"Noble Roar",
"おだてる":"Flatter",
"おちゃかい":"Teatime",
"おどろかす":"Astonish",
"おにび":"Will-O-Wisp",
"おはかまいり":"Last Respects",
"おまじない":"Lucky Chant",
"おんがえし":"Return",
"おんねん":"Grudge",
"ガードシェア":"Guard Split",
"ガードスワップ":"Guard Swap",
"かいでんぱ":"Eerie Impulse",
"かいふくしれい":"Heal Order",
"かいふくふうじ":"Heal Block",
"かいりき":"Strength",
"カウンター":"Counter",
"かえんぐるま":"Flame Wheel",
"かえんだん":"Searing Shot",
"かえんのまもり":"Burning Bulwark",
"かえんほうしゃ":"Flamethrower",
"かえんボール":"Pyro Ball",
"かかとおとし":"Axe Kick",
"かぎわける":"Odor Sleuth",
"かくばる":"Sharpen",
"かげうち":"Shadow Sneak",
"かげぬい":"Spirit Shackle",
"かげぶんしん":"Double Team",
"かぜおこし":"Gust",
"かたきうち":"Retaliate",
"かたくなる":"Harden",
"カタストロフィ":"Ruination",
"かなしばり":"Disable",
"かふんだんご":"Pollen Puff",
"かまいたち":"Razor Wind",
"がまん":"Bide",
"かみくだく":"Crunch",
"かみつく":"Bite",
"かみなり":"Thunder",
"かみなりあらし":"Wildbolt Storm",
"かみなりのキバ":"Thunder Fang",
"かみなりパンチ":"Thunder Punch",
"がむしゃら":"Endeavor",
"からげんき":"Facade",
"からてチョップ":"Karate Chop",
"からではさむ":"Clamp",
"からにこもる":"Withdraw",
"からみつく":"Constrict",
"からをやぶる":"Shell Smash",
"ガリョウテンセイ":"Dragon Ascent",
"かわらわり":"Brick Break",
"がんせきアックス":"Stone Axe",
"がんせきふうじ":"Rock Tomb",
"がんせきほう":"Rock Wrecker",
"きあいだま":"Focus Blast",
"きあいだめ":"Focus Energy",
"きあいパンチ":"Focus Punch",
"ギアソーサー":"Gear Grind",
"ギアチェンジ":"Shift Gear",
"ギガインパクト":"Giga Impact",
"ギガドレイン":"Giga Drain",
"きしかいせい":"Reversal",
"きつけ":"Smelling Salts",
"キノコのほうし":"Spore",
"ギフトパス":"Bestow",
"きまぐレーザー":"Fickle Beam",
"きゅうけつ":"Leech Life",
"きょけんとつげき":"Glaive Rush",
"きょじゅうざん":"Behemoth Blade",
"きょじゅうだん":"Behemoth Bash",
"キラースピン":"Mortal Spin",
"きりさく":"Slash",
"きりばらい":"Defog",
"きりふだ":"Trump Card",
"ぎんいろのかぜ":"Silver Wind",
"キングシールド":"King's Shield",
"きんぞくおん":"Metal Sound",
"クイックターン":"Flip Turn",
"くさのちかい":"Grass Pledge",
"くさぶえ":"Grass Whistle",
"くさむすび":"Grass Knot",
"くさわけ":"Trailblaze",
"くすぐる":"Tickle",
"くちばしキャノン":"Beak Blast",
"クモのす":"Spider Web",
"くらいつく":"Jaw Lock",
"グラススライダー":"Grassy Glide",
"グラスフィールド":"Grassy Terrain",
"グラスミキサー":"Leaf Tornado",
"クラブハンマー":"Crabhammer",
"グランドフォース":"Land's Wrath",
"クリアスモッグ":"Clear Smog",
"くろいきり":"Haze",
"くろいまなざし":"Mean Look",
"グロウパンチ":"Power-Up Punch",
"クロスサンダー":"Fusion Bolt",
"クロスチョップ":"Cross Chop",
"クロスフレイム":"Fusion Flare",
"クロスポイズン":"Cross Poison",
"クロロブラスト":"Chloroblast",
"げきりん":"Outrage",
"けたぐり":"Low Kick",
"ゲップ":"Belch",
"げんしのちから":"Ancient Power",
"コアパニッシャー":"Core Enforcer",
"こうげきしれい":"Attack Order",
"こうごうせい":"Synthesis",
"こうそくいどう":"Agility",
"こうそくスピン":"Rapid Spin",
"ゴーストダイブ":"Phantom Force",
"コーチング":"Coaching",
"コートチェンジ":"Court Change",
"こおりのいぶき":"Frost Breath",
"こおりのキバ":"Ice Fang",
"こおりのつぶて":"Ice Shard",
"コールドフレア":"Ice Burn",
"ゴールドラッシュ":"Make It Rain",
"こがらしあらし":"Bleakwind Storm",
"こごえるかぜ":"Icy Wind",
"こごえるせかい":"Glaciate",
"こころのめ":"Mind Reader",
"コスモパワー":"Cosmic Power",
"ゴッドバード":"Sky Attack",
"コットンガード":"Cotton Guard",
"こなゆき":"Powder Snow",
"このは":"Leafage",
"このゆびとまれ":"Follow Me",
"コメットパンチ":"Meteor Mash",
"こらえる":"Endure",
"ころがる":"Rollout",
"こわいかお":"Scary Face",
"こんげんのはどう":"Origin Pulse",
"さいきのいのり":"Revival Blessing",
"サイケこうせん":"Psybeam",
"サイコウェーブ":"Psywave",
"サイコカッター":"Psycho Cut",
"サイコキネシス":"Psychic",
"サイコシフト":"Psycho Shift",
"サイコショック":"Psyshock",
"サイコノイズ":"Psychic Noise",
"サイコファング":"Psychic Fangs",
"サイコフィールド":"Psychic Terrain",
"サイコブースト":"Psycho Boost",
"サイコブレイク":"Psystrike",
"サイコブレイド":"Psyblade",
"サイドチェンジ":"Ally Switch",
"さいはい":"Instruct",
"さいみんじゅつ":"Hypnosis",
"サウザンアロー":"Thousand Arrows",
"サウザンウェーブ":"Thousand Waves",
"さきおくり":"Quash",
"さきどり":"Me First",
"さしおさえ":"Embargo",
"さばきのつぶて":"Judgment",
"さむいギャグ":"Chilly Reception",
"さわぐ":"Uproar",
"サンダーダイブ":"Supercell Slam",
"サンダープリズン":"Thunder Cage",
"シードフレア":"Seed Flare",
"ジェットパンチ":"Jet Punch",
"シェルアームズ":"Shell Side Arm",
"シェルブレード":"Razor Shell",
"ジオコントロール":"Geomancy",
"しおづけ":"Salt Cure",
"しおふき":"Water Spout",
"しおみず":"Brine",
"シグナルビーム":"Signal Beam",
"じこあんじ":"Psych Up",
"じごくぐるま":"Submission",
"じごくづき":"Throat Chop",
"じこさいせい":"Recover",
"シザークロス":"X-Scissor",
"じしん":"Earthquake",
"しぜんのいかり":"Nature's Madness",
"しぜんのちから":"Nature Power",
"しぜんのめぐみ":"Natural Gift",
"したでなめる":"Lick",
"じたばた":"Flail",
"じだんだ":"Stomping Tantrum",
"しっとのほのお":"Burning Jealousy",
"しっぺがえし":"Payback",
"しっぽきり":"Shed Tail",
"しっぽをふる":"Tail Whip",
"じならし":"Bulldoze",
"しねんのずつき":"Zen Headbutt",
"じばく":"Self-Destruct",
"じばそうさ":"Magnetic Flux",
"しびれごな":"Stun Spore",
"しぼりとる":"Wring Out",
"しめつける":"Bind",
"ジャイロボール":"Gyro Ball",
"シャカシャカほう":"Matcha Gotcha",
"シャドークロー":"Shadow Claw",
"シャドースチール":"Spectral Thief",
"シャドーダイブ":"Shadow Force",
"シャドーパンチ":"Shadow Punch",
"シャドーボール":"Shadow Ball",
"シャドーボーン":"Shadow Bone",
"シャドーレイ":"Moongeist Beam",
"じゃどくのくさり":"Malignant Chain",
"じゃれつく":"Play Rough",
"ジャングルヒール":"Jungle Healing",
"じゅうでん":"Charge",
"じゅうりょく":"Gravity",
"じょうか":"Purify",
"しょうりのまい":"Victory Dance",
"しろいきり":"Mist",
"じわれ":"Fissure",
"しんくうは":"Vacuum Wave",
"シンクロノイズ":"Synchronoise",
"しんそく":"Extreme Speed",
"じんつうりき":"Extrasensory",
"しんぴのちから":"Mystical Power",
"しんぴのつるぎ":"Secret Sword",
"しんぴのまもり":"Safeguard",
"シンプルビーム":"Simple Beam",
"じんらい":"Thunderclap",
"スイープビンタ":"Tail Slap",
"すいとる":"Absorb",
"すいりゅうれんだ":"Surging Strikes",
"スカイアッパー":"Sky Uppercut",
"スキルスワップ":"Skill Swap",
"スケイルショット":"Scale Shot",
"スケイルノイズ":"Clanging Scales",
"スケッチ":"Sketch",
"スターアサルト":"Meteor Assault",
"スチームバースト":"Steam Eruption",
"ずつき":"Headbutt",
"すてゼリフ":"Parting Shot",
"すてみタックル":"Double-Edge",
"ステルスロック":"Stealth Rock",
"ストーンエッジ":"Stone Edge",
"すなあつめ":"Shore Up",
"すなあらし":"Sandstorm",
"すなかけ":"Sand Attack",
"すなじごく":"Sand Tomb",
"スパーク":"Spark",
"スピードスター":"Swift",
"スピードスワップ":"Speed Swap",
"スプーンまげ":"Kinesis",
"スポットライト":"Spotlight",
"スマートホーン":"Smart Strike",
"スモッグ":"Smog",
"すりかえ":"Switcheroo",
"スレッドトラップ":"Silk Trap",
"せいちょう":"Growth",
"せいなるつるぎ":"Sacred Sword",
"せいなるほのお":"Sacred Fire",
"ぜったいれいど":"Sheer Cold",
"そうでん":"Electrify",
"ソウルクラッシュ":"Spirit Break",
"ソウルビート":"Clangorous Soul",
"ソーラービーム":"Solar Beam",
"ソーラーブレード":"Solar Blade",
"ソニックブーム":"Sonic Boom",
"そらをとぶ":"Fly",
"ダークホール":"Dark Void",
"タールショット":"Tar Shot",
"たいあたり":"Tackle",
"だいちのちから":"Earth Power",
"だいちのはどう":"Terrain Pulse",
"だいばくはつ":"Explosion",
"ダイビング":"Dive",
"だいふんげき":"Raging Fury",
"ダイマックスほう":"Dynamax Cannon",
"だいもんじ":"Fire Blast",
"ダイヤストーム":"Diamond Storm",
"たがやす":"Rototiller",
"タキオンカッター":"Tachyon Cutter",
"たきのぼり":"Waterfall",
"だくりゅう":"Muddy Water",
"たくわえる":"Stockpile",
"たこがため":"Octolock",
"ダストシュート":"Gunk Shot",
"たたきつける":"Slam",
"たたみがえし":"Mat Block",
"たたりめ":"Hex",
"たつまき":"Twister",
"たてこもる":"Shelter",
"タネばくだん":"Seed Bomb",
"タネマシンガン":"Bullet Seed",
"ダブルアタック":"Double Hit",
"ダブルウイング":"Dual Wingbeat",
"ダブルチョップ":"Dual Chop",
"ダブルニードル":"Twineedle",
"ダブルパンツァー":"Double Iron Bash",
"タマゴうみ":"Soft-Boiled",
"タマゴばくだん":"Egg Bomb",
"だましうち":"Feint Attack",
"たまなげ":"Barrage",
"ダメおし":"Assurance",
"だんがいのつるぎ":"Precipice Blades",
"ちいさくなる":"Minimize",
"ちからをすいとる":"Strength Sap",
"ちきゅうなげ":"Seismic Toss",
"チャージビーム":"Charge Beam",
"チャームボイス":"Disarming Voice",
"ちょうおんぱ":"Supersonic",
"ちょうのまい":"Quiver Dance",
"ちょうはつ":"Taunt",
"ついばむ":"Pluck",
"ツインビーム":"Twin Beam",
"つきのひかり":"Moonlight",
"つけあがる":"Power Trip",
"つじぎり":"Night Slash",
"ツタこんぼう":"Ivy Cudgel",
"つつく":"Peck",
"つっぱり":"Arm Thrust",
"つのでつく":"Horn Attack",
"つのドリル":"Horn Drill",
"つばさでうつ":"Wing Attack",
"つばめがえし":"Aerial Ace",
"つぶらなひとみ":"Baby-Doll Eyes",
"つぼをつく":"Acupressure",
"つめとぎ":"Hone Claws",
"つららおとし":"Icicle Crash",
"つららばり":"Icicle Spear",
"つるぎのまい":"Swords Dance",
"つるのムチ":"Vine Whip",
"であいがしら":"First Impression",
"てかげん":"Hold Back",
"デカハンマー":"Gigaton Hammer",
"テクスチャー":"Conversion",
"テクスチャー２":"Conversion 2",
"テクノバスター":"Techno Blast",
"デコレーション":"Decorate",
"デスウイング":"Oblivion Wing",
"てだすけ":"Helping Hand",
"てっていこうせん":"Steel Beam",
"てっぺき":"Iron Defense",
"テラクラスター":"Tera Starstorm",
"テラバースト":"Tera Blast",
"テレキネシス":"Telekinesis",
"テレポート":"Teleport",
"てをつなぐ":"Hold Hands",
"でんきショック":"Thunder Shock",
"でんげきくちばし":"Bolt Beak",
"でんげきは":"Shock Wave",
"でんこうせっか":"Quick Attack",
"でんこうそうげき":"Double Shock",
"てんしのキッス":"Sweet Kiss",
"でんじは":"Thunder Wave",
"でんじふゆう":"Magnet Rise",
"でんじほう":"Zap Cannon",
"とおせんぼう":"Block",
"トーチカ":"Baneful Bunker",
"とおぼえ":"Howl",
"とぎすます":"Laser Focus",
"ときのほうこう":"Roar of Time",
"どくガス":"Poison Gas",
"どくづき":"Poison Jab",
"どくどく":"Toxic",
"どくどくのキバ":"Poison Fang",
"どくのいと":"Toxic Thread",
"どくのこな":"Poison Powder",
"どくばり":"Poison Sting",
"どくばりセンボン":"Barb Barrage",
"どくびし":"Toxic Spikes",
"とぐろをまく":"Coil",
"とげキャノン":"Spike Cannon",
"どげざつき":"False Surrender",
"ドゲザン":"Kowtow Cleave",
"とける":"Acid Armor",
"とっしん":"Take Down",
"とっておき":"Last Resort",
"とどめばり":"Fell Stinger",
"とびかかる":"Lunge",
"とびげり":"Jump Kick",
"とびつく":"Pounce",
"とびはねる":"Bounce",
"とびひざげり":"High Jump Kick",
"ともえなげ":"Circle Throw",
"トライアタック":"Tri Attack",
"ドラゴンアロー":"Dragon Darts",
"ドラゴンエール":"Dragon Cheer",
"ドラゴンエナジー":"Dragon Energy",
"ドラゴンクロー":"Dragon Claw",
"ドラゴンダイブ":"Dragon Rush",
"ドラゴンテール":"Dragon Tail",
"ドラゴンハンマー":"Dragon Hammer",
"トラップシェル":"Shell Trap",
"トラバサミ":"Snap Trap",
"ドラムアタック":"Drum Beating",
"トリック":"Trick",
"トリックガード":"Crafty Shield",
"トリックフラワー":"Flower Trick",
"トリックルーム":"Trick Room",
"トリプルアクセル":"Triple Axel",
"トリプルキック":"Triple Kick",
"トリプルダイブ":"Triple Dive",
"ドリルくちばし":"Drill Peck",
"ドリルライナー":"Drill Run",
"ドレインキッス":"Draining Kiss",
"ドレインパンチ":"Drain Punch",
"どろあそび":"Mud Sport",
"どろかけ":"Mud-Slap",
"どろばくだん":"Mud Bomb",
"トロピカルキック":"Trop Kick",
"どろぼう":"Thief",
"ドわすれ":"Amnesia",
"とんぼがえり":"U-turn",
"ないしょばなし":"Confide",
"ナイトバースト":"Night Daze",
"ナイトヘッド":"Night Shade",
"なかまづくり":"Entrainment",
"なかよくする":"Play Nice",
"なきごえ":"Growl",
"なげつける":"Fling",
"なしくずし":"Chip Away",
"なまける":"Slack Off",
"なみだめ":"Tearful Look",
"なみのり":"Surf",
"なやみのタネ":"Worry Seed",
"なりきり":"Role Play",
"ニードルアーム":"Needle Arm",
"ニードルガード":"Spiky Shield",
"にぎりつぶす":"Crush Grip",
"にどげり":"Double Kick",
"ニトロチャージ":"Flame Charge",
"にほんばれ":"Sunny Day",
"にらみつける":"Leer",
"ねがいごと":"Wish",
"ねこだまし":"Fake Out",
"ねごと":"Sleep Talk",
"ネコにこばん":"Pay Day",
"ねこのて":"Assist",
"ネズミざん":"Population Bomb",
"ねっさのあらし":"Sandsear Storm",
"ねっさのだいち":"Scorching Sands",
"ねっとう":"Scald",
"ねっぷう":"Heat Wave",
"ねばねばネット":"Sticky Web",
"ねむりごな":"Sleep Powder",
"ねむる":"Rest",
"ねらいうち":"Snipe Shot",
"ねをはる":"Ingrain",
"ねんりき":"Confusion",
"のしかかり":"Body Slam",
"のみこむ":"Swallow",
"のろい":"Curse",
"バークアウト":"Snarl",
"ハートスタンプ":"Heart Stamp",
"ハートスワップ":"Heart Swap",
"ハードプラント":"Frenzy Plant",
"ハードプレス":"Hard Press",
"ハードローラー":"Steamroller",
"はいすいのじん":"No Retreat",
"ハイドロカノン":"Hydro Cannon",
"ハイドロスチーム":"Hydro Steam",
"ハイドロポンプ":"Hydro Pump",
"ハイパードリル":"Hyper Drill",
"ハイパーボイス":"Hyper Voice",
"はいよるいちげき":"Skitter Smack",
"はかいこうせん":"Hyper Beam",
"ばかぢから":"Superpower",
"はがねのつばさ":"Steel Wing",
"はきだす":"Spit Up",
"ばくおんぱ":"Boomburst",
"ばくれつパンチ":"Dynamic Punch",
"ハサミギロチン":"Guillotine",
"はさむ":"Vise Grip",
"はじけるほのお":"Flame Burst",
"はたきおとす":"Knock Off",
"はたく":"Pound",
"はっけい":"Force Palm",
"はっぱカッター":"Razor Leaf",
"ハッピータイム":"Happy Hour",
"はどうだん":"Aura Sphere",
"バトンタッチ":"Baton Pass",
"はなびらのまい":"Petal Dance",
"はなふぶき":"Petal Blizzard",
"はねやすめ":"Roost",
"はねる":"Splash",
"ハバネロエキス":"Spicy Extract",
"バブルこうせん":"Bubble Beam",
"はめつのねがい":"Doom Desire",
"はやてがえし":"Upper Hand",
"はらだいこ":"Belly Drum",
"パラボラチャージ":"Parabolic Charge",
"バリアー":"Barrier",
"バリアーラッシュ":"Psyshield Bash",
"はるのあらし":"Springtide Storm",
"バレットパンチ":"Bullet Punch",
"ハロウィン":"Trick-or-Treat",
"パワーウィップ":"Power Whip",
"パワーシェア":"Power Split",
"パワージェム":"Power Gem",
"パワーシフト":"Power Shift",
"パワースワップ":"Power Swap",
"パワートリック":"Power Trick",
"パワフルエッジ":"Mighty Cleave",
"ヒートスタンプ":"Heat Crash",
"ひかりのかべ":"Light Screen",
"ひけん・ちえなみ":"Ceaseless Edge",
"ひっかく":"Scratch",
"ひっくりかえす":"Topsy-Turvy",
"ビックリヘッド":"Mind Blown",
"ひっさつまえば":"Hyper Fang",
"ひのこ":"Ember",
"ひみつのちから":"Secret Power",
"ひゃっきやこう":"Infernal Parade",
"ひやみず":"Chilling Water",
"ひょうざんおろし":"Mountain Gale",
"ピヨピヨパンチ":"Dizzy Punch",
"びりびりちくちく":"Zing Zap",
"ビルドアップ":"Bulk Up",
"ファストガード":"Quick Guard",
"ふいうち":"Sucker Punch",
"ふういん":"Imprison",
"フェアリーロック":"Fairy Lock",
"フェイタルクロー":"Dire Claw",
"フェイント":"Feint",
"フェザーダンス":"Feather Dance",
"フォトンゲイザー":"Photon Geyser",
"ふきとばし":"Whirlwind",
"ぶきみなじゅもん":"Eerie Spell",
"ふくろだたき":"Beat Up",
"ふしょくガス":"Corrosive Gas",
"ぶちかまし":"Headlong Rush",
"ふぶき":"Blizzard",
"ふみつけ":"Stomp",
"フライングプレス":"Flying Press",
"ブラストバーン":"Blast Burn",
"プラズマシャワー":"Ion Deluge",
"プラズマフィスト":"Plasma Fists",
"フラッシュ":"Flash",
"ブラッドムーン":"Blood Moon",
"フラフラダンス":"Teeter Dance",
"フラワーガード":"Flower Shield",
"フラワーヒール":"Floral Healing",
"フリーズドライ":"Freeze-Dry",
"フリーズボルト":"Freeze Shock",
"フリーフォール":"Sky Drop",
"ブリザードランス":"Glacial Lance",
"プリズムレーザー":"Prismatic Laser",
"ふるいたてる":"Work Up",
"フルールカノン":"Fleur Cannon",
"フレアソング":"Torch Song",
"フレアドライブ":"Flare Blitz",
"ブレイククロー":"Crush Claw",
"ブレイズキック":"Blaze Kick",
"ブレイブチャージ":"Take Heart",
"ブレイブバード":"Brave Bird",
"プレゼント":"Present",
"ブロッキング":"Obstruct",
"ふんえん":"Lava Plume",
"ふんか":"Eruption",
"ふんじん":"Powder",
"ふんどのこぶし":"Rage Fist",
"ぶんまわす":"Brutal Swing",
"ヘドロウェーブ":"Sludge Wave",
"ヘドロこうげき":"Sludge",
"ヘドロばくだん":"Sludge Bomb",
"ベノムショック":"Venoshock",
"ベノムトラップ":"Venom Drench",
"ヘビーボンバー":"Heavy Slam",
"へびにらみ":"Glare",
"へんしん":"Transform",
"ホイールスピン":"Spin Out",
"ポイズンテール":"Poison Tail",
"ぼうぎょしれい":"Defend Order",
"ほうでん":"Discharge",
"ぼうふう":"Hurricane",
"ほうふく":"Comeuppance",
"ほえる":"Roar",
"ほおばる":"Stuff Cheeks",
"ボーンラッシュ":"Bone Rush",
"ほごしょく":"Camouflage",
"ほしがる":"Covet",
"ほたるび":"Tail Glow",
"ほっぺすりすり":"Nuzzle",
"ボディパージ":"Autotomize",
"ボディプレス":"Body Press",
"ホネこんぼう":"Bone Club",
"ホネブーメラン":"Bonemerang",
"ほのおのうず":"Fire Spin",
"ほのおのキバ":"Fire Fang",
"ほのおのちかい":"Fire Pledge",
"ほのおのパンチ":"Fire Punch",
"ほのおのまい":"Fiery Dance",
"ほのおのムチ":"Fire Lash",
"ポルターガイスト":"Poltergeist",
"ボルテッカー":"Volt Tackle",
"ボルトチェンジ":"Volt Switch",
"ほろびのうた":"Perish Song",
"まきつく":"Wrap",
"まきびし":"Spikes",
"マグニチュード":"Magnitude",
"マグネットボム":"Magnet Bomb",
"マグマストーム":"Magma Storm",
"マジカルシャイン":"Dazzling Gleam",
"マジカルフレイム":"Mystical Fire",
"マジカルリーフ":"Magical Leaf",
"マジックコート":"Magic Coat",
"マジックルーム":"Magic Room",
"マッドショット":"Mud Shot",
"マッハパンチ":"Mach Punch",
"まとわりつく":"Infestation",
"まねっこ":"Copycat",
"まほうのこな":"Magic Powder",
"まもる":"Protect",
"まるくなる":"Defense Curl",
"マルチアタック":"Multi-Attack",
"まわしげり":"Rolling Kick",
"みかづきのいのり":"Lunar Blessing",
"みかづきのまい":"Lunar Dance",
"みがわり":"Substitute",
"みきり":"Detect",
"ミサイルばり":"Pin Missile",
"みずあそび":"Water Sport",
"みずあめボム":"Syrup Bomb",
"みずしゅりけん":"Water Shuriken",
"みずでっぽう":"Water Gun",
"ミストバースト":"Misty Explosion",
"ミストフィールド":"Misty Terrain",
"ミストボール":"Mist Ball",
"みずのちかい":"Water Pledge",
"みずのはどう":"Water Pulse",
"みずびたし":"Soak",
"みだれづき":"Fury Attack",
"みだれひっかき":"Fury Swipes",
"みちづれ":"Destiny Bond",
"みねうち":"False Swipe",
"みやぶる":"Foresight",
"ミラーコート":"Mirror Coat",
"ミラーショット":"Mirror Shot",
"ミラータイプ":"Reflect Type",
"みらいよち":"Future Sight",
"ミラクルアイ":"Miracle Eye",
"ミルクのみ":"Milk Drink",
"みわくのボイス":"Alluring Voice",
"みをけずる":"Fillet Away",
"ムーンフォース":"Moonblast",
"ムゲンダイビーム":"Eternabeam",
"むしくい":"Bug Bite",
"むしのさざめき":"Bug Buzz",
"むしのていこう":"Struggle Bug",
"むねんのつるぎ":"Bitter Blade",
"めいそう":"Calm Mind",
"メガドレイン":"Mega Drain",
"メガトンキック":"Mega Kick",
"メガトンパンチ":"Mega Punch",
"メガホーン":"Megahorn",
"めざましビンタ":"Wake-Up Slap",
"めざめるダンス":"Revelation Dance",
"めざめるパワー":"Hidden Power",
"メタルクロー":"Metal Claw",
"メタルバースト":"Metal Burst",
"メテオドライブ":"Sunsteel Strike",
"メテオビーム":"Meteor Beam",
"メロメロ":"Attract",
"もえあがるいかり":"Fiery Wrath",
"もえつきる":"Burn Up",
"ものまね":"Mimic",
"もりののろい":"Forest's Curse",
"もろはのずつき":"Head Smash",
"やきつくす":"Incinerate",
"やけっぱち":"Temper Flare",
"やつあたり":"Frustration",
"やどりぎのタネ":"Leech Seed",
"やまあらし":"Storm Throw",
"ゆうわく":"Captivate",
"ゆきげしき":"Snowscape",
"ゆきなだれ":"Avalanche",
"ゆびをふる":"Metronome",
"ゆめくい":"Dream Eater",
"ようかいえき":"Acid",
"ようせいのかぜ":"Fairy Wind",
"ヨガのポーズ":"Meditate",
"よこどり":"Snatch",
"らいげき":"Bolt Strike",
"ライジングボルト":"Rising Voltage",
"らいめいげり":"Thunderous Kick",
"ラスターカノン":"Flash Cannon",
"ラスターパージ":"Luster Purge",
"リーフストーム":"Leaf Storm",
"リーフブレード":"Leaf Blade",
"リサイクル":"Recycle",
"リフレクター":"Reflect",
"リフレッシュ":"Refresh",
"リベンジ":"Revenge",
"りゅうせいぐん":"Draco Meteor",
"りゅうのいかり":"Dragon Rage",
"りゅうのいぶき":"Dragon Breath",
"りゅうのはどう":"Dragon Pulse",
"りゅうのまい":"Dragon Dance",
"りんごさん":"Apple Acid",
"りんしょう":"Round",
"ルミナコリジョン":"Lumina Crash",
"レイジングブル":"Raging Bull",
"れいとうパンチ":"Ice Punch",
"れいとうビーム":"Ice Beam",
"れんごく":"Inferno",
"れんぞくぎり":"Fury Cutter",
"れんぞくパンチ":"Comet Punch",
"ローキック":"Low Sweep",
"ロケットずつき":"Skull Bash",
"ロックオン":"Lock-On",
"ロックカット":"Rock Polish",
"ロッククライム":"Rock Climb",
"ロックブラスト":"Rock Blast",
"ワイドガード":"Wide Guard",
"ワイドフォース":"Expanding Force",
"ワイドブレイカー":"Breaking Swipe",
"ワイルドボルト":"Wild Charge",
"わたほうし":"Cotton Spore",
"わるあがき":"Struggle",
"わるだくみ":"Nasty Plot",
"ワンダースチーム":"Strange Steam",
"ワンダールーム":"Wonder Room",
},
"ability": {
"ＡＲシステム":"RKS System",
"あついしぼう":"Thick Fat",
"アナライズ":"Analytic",
"いろめがね":"Tinted Lens",
"いわはこび":"Rocky Payload",
"うるおいボイス":"Liquid Voice",
"エレキスキン":"Galvanize",
"オーラブレイク":"Aura Break",
"おやこあい":"Parental Bond",
"かがくへんかガス":"Neutralizing Gas",
"かたいツメ":"Tough Claws",
"かたやぶり":"Mold Breaker",
"カブトアーマー":"Battle Armor",
"がんじょうあご":"Strong Jaw",
"かんそうはだ":"Dry Skin",
"きずなへんげ":"Battle Bond",
"きもったま":"Scrappy",
"きよめのしお":"Purifying Salt",
"きれあじ":"Sharpness",
"クォークチャージ":"Quark Drive",
"くさのけがわ":"Grass Pelt",
"げきりゅう":"Torrent",
"こおりのりんぷん":"Ice Scales",
"こだいかっせい":"Protosynthesis",
"ごりむちゅう":"Gorilla Tactics",
"こんじょう":"Guts",
"サンパワー":"Solar Power",
"シェルアーマー":"Shell Armor",
"しんがん":"Mind's Eye",
"しんりょく":"Overgrow",
"すいほう":"Water Bubble",
"スカイスキン":"Aerilate",
"スキルリンク":"Skill Link",
"すてみ":"Reckless",
"スナイパー":"Sniper",
"すなのちから":"Sand Force",
"すりぬけ":"Infiltrator",
"スロースタート":"Slow Start",
"そうだいしょう":"Supreme Overlord",
"ダークオーラ":"Dark Aura",
"ターボブレイズ":"Turboblaze",
"たいねつ":"Heatproof",
"ちからずく":"Sheer Force",
"ちからもち":"Huge Power",
"てきおうりょく":"Adaptability",
"テクニシャン":"Technician",
"てつのこぶし":"Iron Fist",
"テラスシェル":"Tera Shell",
"テラボルテージ":"Teravolt",
"てんねん":"Unaware",
"とうそうしん":"Rivalry",
"どくぼうそう":"Toxic Boost",
"トランジスタ":"Transistor",
"ねつぼうそう":"Flare Boost",
"ノーマルスキン":"Normalize",
"ハードロック":"Solid Rock",
"はがねつかい":"Steelworker",
"はがねのせいしん":"Steely Spirit",
"バッテリー":"Battery",
"ハドロンエンジン":"Hadron Engine",
"はりきり":"Hustle",
"はりこみ":"Stakeout",
"パワースポット":"Power Spot",
"パンクロック":"Punk Rock",
"ばんけん":"Guard Dog",
"ひひいろのこどう":"Orichalcum Pulse",
"ファーコート":"Fur Coat",
"ファントムガード":"Shadow Shield",
"フィルター":"Filter",
"フェアリーオーラ":"Fairy Aura",
"フェアリースキン":"Pixilate",
"ふくつのたて":"Dauntless Shield",
"ふしぎなうろこ":"Marvel Scale",
"ふとうのけん":"Intrepid Sword",
"ふゆう":"Levitate",
"プラス":"Plus",
"フラワーギフト":"Flower Gift",
"フリーズスキン":"Refrigerate",
"プリズムアーマー":"Prism Armor",
"ブレインフォース":"Neuroforce",
"フレンドガード":"Friend Guard",
"ヘヴィメタル":"Heavy Metal",
"へんげんじざい":"Protean",
"ぼうじん":"Overcoat",
"マイナス":"Minus",
"マルチスケイル":"Multiscale",
"むしのしらせ":"Swarm",
"メガランチャー":"Mega Launcher",
"もうか":"Blaze",
"もふもふ":"Fluffy",
"もらいび":"Flash Fire",
"ヨガパワー":"Pure Power",
"よわき":"Defeatist",
"ライトメタル":"Light Metal",
"リベロ":"Libero",
"りゅうのあぎと":"Dragon's Maw",
"わざわいのうつわ":"Vessel of Ruin",
"わざわいのおふだ":"Tablets of Ruin",
"わざわいのたま":"Beads of Ruin",
"わざわいのつるぎ":"Sword of Ruin",
"アイスフェイス":"Ice Face",
"アイスボディ":"Ice Body",
"あくしゅう":"Stench",
"あとだし":"Stall",
"あまのじゃく":"Contrary",
"あめうけざら":"Rain Dish",
"あめふらし":"Drizzle",
"ありじごく":"Arena Trap",
"アロマベール":"Aroma Veil",
"いかく":"Intimidate",
"いかりのこうら":"Anger Shell",
"いかりのつぼ":"Anger Point",
"いしあたま":"Rock Head",
"いたずらごころ":"Prankster",
"いやしのこころ":"Healer",
"イリュージョン":"Illusion",
"うのミサイル":"Gulp Missile",
"うるおいボディ":"Hydration",
"エアロック":"Air Lock",
"エレキメイカー":"Electric Surge",
"えんかく":"Long Reach",
"おうごんのからだ":"Good as Gold",
"おどりこ":"Dancer",
"おみとおし":"Frisk",
"おもかげやどし":"Embody Aspect",
"おもてなし":"Hospitality",
"おわりのだいち":"Desolate Land",
"カーリーヘアー":"Tangling Hair",
"かいりきバサミ":"Hyper Cutter",
"かがくのちから":"Power of Alchemy",
"かげふみ":"Shadow Tag",
"かぜのり":"Wind Rider",
"かそく":"Speed Boost",
"かちき":"Competitive",
"かるわざ":"Unburden",
"かわりもの":"Imposter",
"がんじょう":"Sturdy",
"かんろなミツ":"Supersweet Syrup",
"ききかいひ":"Emergency Exit",
"きけんよち":"Anticipation",
"ぎたい":"Mimicry",
"きみょうなくすり":"Curious Medicine",
"ぎゃくじょう":"Berserk",
"きゅうばん":"Suction Cups",
"きょううん":"Super Luck",
"きょうえん":"Costar",
"きょうせい":"Symbiosis",
"ぎょぐん":"Schooling",
"きんしのちから":"Mycelium Might",
"きんちょうかん":"Unnerve",
"くいしんぼう":"Gluttony",
"クイックドロウ":"Quick Draw",
"くだけるよろい":"Weak Armor",
"グラスメイカー":"Grassy Surge",
"クリアボディ":"Clear Body",
"くろのいななき":"As One (Spectrier)",
"こぼれダネ":"Seed Sower",
"こんがりボディ":"Well-Baked Body",
"サイコメイカー":"Psychic Surge",
"さいせいりょく":"Regenerator",
"さまようたましい":"Wandering Spirit",
"さめはだ":"Rough Skin",
"じきゅうりょく":"Stamina",
"じしんかじょう":"Moxie",
"しぜんかいふく":"Natural Cure",
"しめりけ":"Damp",
"しゅうかく":"Harvest",
"じゅうなん":"Limber",
"じゅくせい":"Ripen",
"じょうききかん":"Steam Engine",
"しょうりのほし":"Victory Star",
"じょおうのいげん":"Queenly Majesty",
"じりょく":"Magnet Pull",
"しれいとう":"Commander",
"しろいけむり":"White Smoke",
"しろのいななき":"As One (Glastrier)",
"シンクロ":"Synchronize",
"じんばいったい":"As One",
"スイートベール":"Sweet Veil",
"すいすい":"Swift Swim",
"スクリューおびれ":"Propeller Tail",
"すじがねいり":"Stalwart",
"すなおこし":"Sand Stream",
"すなかき":"Sand Rush",
"すながくれ":"Sand Veil",
"すなはき":"Sand Spit",
"するどいめ":"Keen Eye",
"スワームチェンジ":"Power Construct",
"せいぎのこころ":"Justified",
"せいしんりょく":"Inner Focus",
"せいでんき":"Static",
"ぜったいねむり":"Comatose",
"ゼロフォーミング":"Teraform Zero",
"そうしょく":"Sap Sipper",
"ソウルハート":"Soul-Heart",
"ダウンロード":"Download",
"だっぴ":"Shed Skin",
"たまひろい":"Ball Fetch",
"ダルマモード":"Zen Mode",
"たんじゅん":"Simple",
"ちくでん":"Volt Absorb",
"ちどりあし":"Tangled Feet",
"ちょすい":"Water Absorb",
"テイルアーマー":"Armor Tail",
"てつのトゲ":"Iron Barbs",
"テラスチェンジ":"Tera Shift",
"デルタストリーム":"Delta Stream",
"テレパシー":"Telepathy",
"でんきエンジン":"Motor Drive",
"でんきにかえる":"Electromorphosis",
"てんきや":"Forecast",
"てんのめぐみ":"Serene Grace",
"どくくぐつ":"Poison Puppeteer",
"どくげしょう":"Toxic Debris",
"どくしゅ":"Poison Touch",
"どくのくさり":"Toxic Chain",
"どくのトゲ":"Poison Point",
"どしょく":"Earth Eater",
"とびだすなかみ":"Innards Out",
"トレース":"Trace",
"とれないにおい":"Lingering Aroma",
"どんかん":"Oblivious",
"ナイトメア":"Bad Dreams",
"なまけ":"Truant",
"にげあし":"Run Away",
"にげごし":"Wimp Out",
"ぬめぬめ":"Gooey",
"ねつこうかん":"Thermal Exchange",
"ねんちゃく":"Sticky Hold",
"ノーガード":"No Guard",
"ノーてんき":"Cloud Nine",
"のろわれボディ":"Cursed Body",
"ばけのかわ":"Disguise",
"はじまりのうみ":"Primordial Sea",
"パステルベール":"Pastel Veil",
"はっこう":"Illuminate",
"はとむね":"Big Pecks",
"バトルスイッチ":"Stance Change",
"はやあし":"Quick Feet",
"はやおき":"Early Bird",
"はやてのつばさ":"Gale Wings",
"はらぺこスイッチ":"Hunger Switch",
"バリアフリー":"Screen Cleaner",
"はんすう":"Cud Chew",
"ビーストブースト":"Beast Boost",
"ヒーリングシフト":"Triage",
"ひでり":"Drought",
"ひとでなし":"Merciless",
"ビビッドボディ":"Dazzling",
"びびり":"Rattled",
"ひらいしん":"Lightning Rod",
"びんじょう":"Opportunist",
"ふうりょくでんき":"Wind Power",
"ふかしのこぶし":"Unseen Fist",
"ぶきよう":"Klutz",
"ふくがん":"Compound Eyes",
"ふくつのこころ":"Steadfast",
"ふしぎなまもり":"Wonder Guard",
"ふしょく":"Corrosion",
"ふみん":"Insomnia",
"フラワーベール":"Flower Veil",
"プレッシャー":"Pressure",
"ヘドロえき":"Liquid Ooze",
"へんしょく":"Color Change",
"ポイズンヒール":"Poison Heal",
"ぼうおん":"Soundproof",
"ほうし":"Effect Spore",
"ぼうだん":"Bulletproof",
"ほおぶくろ":"Cheek Pouch",
"ほのおのからだ":"Flame Body",
"ほろびのボディ":"Perish Body",
"マイティチェンジ":"Zero to Hero",
"マイペース":"Own Tempo",
"マグマのよろい":"Magma Armor",
"まけんき":"Defiant",
"マジシャン":"Magician",
"マジックガード":"Magic Guard",
"マジックミラー":"Magic Bounce",
"マルチタイプ":"Multitype",
"ミイラ":"Mummy",
"みずがため":"Water Compaction",
"ミストメイカー":"Misty Surge",
"みずのベール":"Water Veil",
"みつあつめ":"Honey Gather",
"ミラーアーマー":"Mirror Armor",
"ミラクルスキン":"Wonder Skin",
"ムラっけ":"Moody",
"メタルプロテクト":"Full Metal Body",
"メロメロボディ":"Cute Charm",
"めんえき":"Immunity",
"ものひろい":"Pickup",
"やるき":"Vital Spirit",
"ゆうばく":"Aftermath",
"ゆきかき":"Slush Rush",
"ゆきがくれ":"Snow Cloak",
"ゆきふらし":"Snow Warning",
"ようりょくそ":"Chlorophyll",
"よちむ":"Forewarn",
"よびみず":"Storm Drain",
"リーフガード":"Leaf Guard",
"リミットシールド":"Shields Down",
"りんぷん":"Shield Dust",
"レシーバー":"Receiver",
"わたげ":"Cotton Down",
"わるいてぐせ":"Pickpocket",
},
"item": {
"あいいろのたま":"Blue Orb",
"アイスメモリ":"Ice Memory",
"あおいバンダナ":"Blue Scarf",
"あおぞらプレート":"Sky Plate",
"あかいいと":"Destiny Knot",
"あかいバンダナ":"Red Scarf",
"アクZ":"Darkinium Z",
"アクアカセット":"Douse Drive",
"あくのジュエル":"Dark Gem",
"アシレーヌZ":"Primarium Z",
"あついいわ":"Heat Rock",
"アッキのみ":"Kee Berry",
"あつぞこブーツ":"Heavy-Duty Boots",
"アップグレード":"Up-Grade",
"アブソルナイト":"Absolite",
"あやしいおこう":"Odd Incense",
"あやしいパッチ":"Dubious Disc",
"アロライZ":"Aloraichium Z",
"イアのみ":"Iapapa Berry",
"イーブイZ":"Eevium Z",
"いかさまダイス":"Loaded Dice",
"いかずちプレート":"Zap Plate",
"いしずえのめん":"Cornerstone Mask",
"イトケのみ":"Passho Berry",
"いどのめん":"Wellspring Mask",
"イナズマカセット":"Shock Drive",
"いのちのたま":"Life Orb",
"イバンのみ":"Custap Berry",
"イワZ":"Rockium Z",
"いわのジュエル":"Rock Gem",
"ウイのみ":"Wiki Berry",
"ウオーターメモリ":"Water Memory",
"うしおのおこう":"Sea Incense",
"ウタンのみ":"Payapa Berry",
"ウルトラネクロZ":"Ultranecrozium Z",
"エスパーZ":"Psychium Z",
"エスパージュエル":"Psychic Gem",
"エルレイドナイト":"Galladite",
"エレキシード":"Electric Seed",
"エレキブースター":"Electirizer",
"エレクトロメモリ":"Electric Memory",
"おうじゃのしるし":"King's Rock",
"おおきなねっこ":"Big Root",
"オッカのみ":"Occa Berry",
"オニゴーリナイト":"Glalitite",
"おはなのおこう":"Rose Incense",
"オボンのみ":"Sitrus Berry",
"おまもりこばん":"Amulet Coin",
"オレンのみ":"Oran Berry",
"おんみつマント":"Covert Cloak",
"かいがらのすず":"Shell Bell",
"カイロスナイト":"Pinsirite",
"かえんだま":"Flame Orb",
"ガオガエンZ":"Incinium Z",
"カクトウZ":"Fightinium Z",
"かくとうジュエル":"Fighting Gem",
"カゴのみ":"Chesto Berry",
"カシブのみ":"Kasib Berry",
"かたいいし":"Hard Stone",
"カビゴンZ":"Snorlium Z",
"カプZ":"Tapunium Z",
"ガブリアスナイト":"Garchompite",
"かまどのめん":"Hearthflame Mask",
"カムラのみ":"Salac Berry",
"カメックスナイト":"Blastoisinite",
"からぶりほけん":"Blunder Policy",
"かるいし":"Float Stone",
"ガルーラナイト":"Kangaskhanite",
"かわらずのいし":"Everstone",
"がんせきおこう":"Rock Incense",
"がんせきプレート":"Stone Plate",
"きあいのタスキ":"Focus Sash",
"きあいのハチマキ":"Focus Band",
"キーのみ":"Persim Berry",
"きいろのバンダナ":"Yellow Scarf",
"きせきのタネ":"Miracle Seed",
"ギャラドスナイト":"Gyaradosite",
"きゅうこん":"Absorb Bulb",
"きょうせいギプス":"Macho Brace",
"きよめのおこう":"Pure Incense",
"きよめのおふだ":"Cleanse Tag",
"きれいなウロコ":"Prism Scale",
"きれいなぬけがら":"Shed Shell",
"ぎんのこな":"Silver Powder",
"クサZ":"Grassium Z",
"くさのジュエル":"Grass Gem",
"クチートナイト":"Mawilite",
"くちたけん":"Rusted Sword",
"くちたたて":"Rusted Shield",
"くっつきバリ":"Sticky Barb",
"グラウンドメモリ":"Ground Memory",
"グラスシード":"Grassy Seed",
"グラスメモリ":"Grass Memory",
"クラボのみ":"Cheri Berry",
"グランドコート":"Terrain Extender",
"クリアチャーム":"Clear Amulet",
"くろいてっきゅう":"Iron Ball",
"くろいヘドロ":"Black Sludge",
"くろいメガネ":"Black Glasses",
"くろおび":"Black Belt",
"けむりだま":"Smoke Ball",
"ゲンガナイト":"Gengarite",
"こううんのおこう":"Luck Incense",
"こうかくレンズ":"Wide Lens",
"こうこうのしっぽ":"Lagging Tail",
"こうてつプレート":"Iron Plate",
"ゴーストZ":"Ghostium Z",
"ゴーストジュエル":"Ghost Gem",
"ゴーストメモリ":"Ghost Memory",
"コオリZ":"Icium Z",
"こおりのジュエル":"Ice Gem",
"こころのしずく":"Soul Dew",
"こだわりスカーフ":"Choice Scarf",
"こだわりハチマキ":"Choice Band",
"こだわりメガネ":"Choice Specs",
"ゴツゴツメット":"Rocky Helmet",
"こぶしのプレート":"Fist Plate",
"こわもてプレート":"Dread Plate",
"こんごうだま":"Adamant Orb",
"サーナイトナイト":"Gardevoirite",
"サイキックメモリ":"Psychic Memory",
"サイコシード":"Psychic Seed",
"さざなみのおこう":"Wave Incense",
"サトピカZ":"Pikashunium Z",
"サメハダナイト":"Sharpedonite",
"さらさらいわ":"Smooth Rock",
"サンのみ":"Lansat Berry",
"しあわせタマゴ":"Lucky Egg",
"じしゃく":"Magnet",
"しずくプレート":"Splash Plate",
"しめつけバンド":"Binding Band",
"しめったいわ":"Damp Rock",
"ジメンZ":"Groundium Z",
"じめんのジュエル":"Ground Gem",
"じゃくてんほけん":"Weakness Policy",
"ジャポのみ":"Jaboca Berry",
"ジャラランガZ":"Kommonium Z",
"じゅうでんち":"Cell Battery",
"ジュカインナイト":"Sceptilite",
"シュカのみ":"Shuca Berry",
"ジュナイパーZ":"Decidium Z",
"ジュペッタナイト":"Banettite",
"しらたま":"Lustrous Orb",
"シルクのスカーフ":"Silk Scarf",
"しろいハーブ":"White Herb",
"しんかいのウロコ":"Deep Sea Scale",
"しんかいのキバ":"Deep Sea Tooth",
"しんかのきせき":"Eviolite",
"しんぴのしずく":"Mystic Water",
"ズアのみ":"Apicot Berry",
"スターのみ":"Starf Berry",
"スチールメモリ":"Steel Memory",
"スピアナイト":"Beedrillite",
"スピードパウダー":"Quick Powder",
"するどいキバ":"Razor Fang",
"するどいくちばし":"Sharp Beak",
"するどいツメ":"Razor Claw",
"せいれいプレート":"Pixie Plate",
"せんせいのツメ":"Quick Claw",
"ソクノのみ":"Wacan Berry",
"ソルガレオZ":"Solganium Z",
"ダークメモリ":"Dark Memory",
"だいこんごうだま":"Adamant Crystal",
"だいしらたま":"Lustrous Globe",
"だいちのプレート":"Earth Plate",
"だいはっきんだま":"Griseous Core",
"だっしゅつパック":"Eject Pack",
"だっしゅつボタン":"Eject Button",
"たつじんのおび":"Expert Belt",
"タブンネナイト":"Audinite",
"たべのこし":"Leftovers",
"たまむしプレート":"Insect Plate",
"タラプのみ":"Maranga Berry",
"タンガのみ":"Tanga Berry",
"チーゴのみ":"Rawst Berry",
"チイラのみ":"Liechi Berry",
"ちからのハチマキ":"Muscle Band",
"チャーレムナイト":"Medichamite",
"チルタリスナイト":"Altarianite",
"つめたいいわ":"Icy Rock",
"つららのプレート":"Icicle Plate",
"ディアンシナイト":"Diancite",
"でかいきんのたま":"Big Nugget",
"デンキZ":"Electrium Z",
"でんきだま":"Light Ball",
"でんきのジュエル":"Electric Gem",
"デンリュウナイト":"Ampharosite",
"ドクZ":"Poisonium Z",
"とくせいガード":"Ability Shield",
"どくどくだま":"Toxic Orb",
"どくのジュエル":"Poison Gem",
"とけないこおり":"Never-Melt Ice",
"とつげきチョッキ":"Assault Vest",
"ドラゴンZ":"Dragonium Z",
"ドラゴンジュエル":"Dragon Gem",
"ドラゴンメモリ":"Dragon Memory",
"ナゾのみ":"Enigma Berry",
"ナナシのみ":"Aspear Berry",
"ナモのみ":"Colbur Berry",
"においぶくろ":"Sachet",
"ねばりのかぎづめ":"Grip Claw",
"ねらいのまと":"Ring Target",
"ノーマルZ":"Normalium Z",
"ノーマルジュエル":"Normal Gem",
"のどスプレー":"Throat Spray",
"のろいのおふだ":"Spell Tag",
"のんきのおこう":"Lax Incense",
"はかいのいでんし":"Berserk Gene",
"ハガネZ":"Steelium Z",
"ハガネールナイト":"Steelixite",
"はがねのジュエル":"Steel Gem",
"バクーダナイト":"Cameruptite",
"バグメモリ":"Bug Memory",
"バコウのみ":"Coba Berry",
"バシャーモナイト":"Blazikenite",
"はっきんだま":"Griseous Orb",
"ハッサムナイト":"Scizorite",
"ハバンのみ":"Haban Berry",
"パワーアンクル":"Power Anklet",
"パワーウエイト":"Power Weight",
"パワーバンド":"Power Band",
"パワーベルト":"Power Belt",
"パワーリスト":"Power Bracer",
"パワーレンズ":"Power Lens",
"パワフルハーブ":"Power Herb",
"バンギラスナイト":"Tyranitarite",
"バンジのみ":"Aguav Berry",
"パンチグローブ":"Punching Glove",
"ばんのうがさ":"Utility Umbrella",
"ビアーのみ":"Kebia Berry",
"ピカチュウZ":"Pikanium Z",
"ひかりごけ":"Luminous Moss",
"ひかりのこな":"Bright Powder",
"ひかりのねんど":"Light Clay",
"ヒコウZ":"Flyinium Z",
"ひこうのジュエル":"Flying Gem",
"ピジョットナイト":"Pidgeotite",
"ひのたまプレート":"Flame Plate",
"ビビリだま":"Adrenaline Orb",
"ヒメリのみ":"Leppa Berry",
"ピンクのバンダナ":"Pink Scarf",
"ピンクのリボン":"Pink Bow",
"ピントレンズ":"Scope Lens",
"ファイトメモリ":"Fighting Memory",
"ファイヤーメモリ":"Fire Memory",
"フィラのみ":"Figy Berry",
"ブーストエナジー":"Booster Energy",
"ふうせん":"Air Balloon",
"フーディナイト":"Alakazite",
"フェアリーZ":"Fairium Z",
"フェアリーメモリ":"Fairy Memory",
"フォーカスレンズ":"Zoom Lens",
"ふしぎのプレート":"Mind Plate",
"フシギバナイト":"Venusaurite",
"プテラナイト":"Aerodactylite",
"ふといホネ":"Thick Club",
"フライングメモリ":"Flying Memory",
"フリーズカセット":"Chill Drive",
"ブレイズカセット":"Burn Drive",
"プロテクター":"Protector",
"べにいろのたま":"Red Orb",
"ヘラクロスナイト":"Heracronite",
"ヘルガナイト":"Houndoominite",
"ポイズンメモリ":"Poison Memory",
"ホイップポップ":"Whipped Dream",
"ぼうごパット":"Protective Pads",
"ぼうじんゴーグル":"Safety Goggles",
"ボーマンダナイト":"Salamencite",
"ボスゴドラナイト":"Aggronite",
"ホズのみ":"Chilan Berry",
"ホノオZ":"Firium Z",
"ほのおのジュエル":"Fire Gem",
"マーシャドーZ":"Marshadium Z",
"まがったスプーン":"Twisted Spoon",
"マグマブースター":"Magmarizer",
"マゴのみ":"Mago Berry",
"まんぷくおこう":"Full Incense",
"まんまるいし":"Oval Stone",
"ミクルのみ":"Micle Berry",
"ミズZ":"Waterium Z",
"みずたまリボン":"Polkadot Bow",
"ミストシード":"Misty Seed",
"みずのジュエル":"Water Gem",
"みどりのバンダナ":"Green Scarf",
"みどりのプレート":"Meadow Plate",
"ミミッキュZ":"Mimikium Z",
"ミミロップナイト":"Lopunnite",
"ミュウZ":"Mewnium Z",
"ミュウツナイトX":"Mewtwonite X",
"ミュウツナイトY":"Mewtwonite Y",
"ムシZ":"Buginium Z",
"むしのジュエル":"Bug Gem",
"メタグロスナイト":"Metagrossite",
"メタルコート":"Metal Coat",
"メタルパウダー":"Metal Powder",
"メトロノーム":"Metronome",
"メンタルハーブ":"Mental Herb",
"もうどくプレート":"Toxic Plate",
"もくたん":"Charcoal",
"ものしりメガネ":"Wise Glasses",
"もののけプレート":"Spooky Plate",
"ものまねハーブ":"Mirror Herb",
"モモンのみ":"Pecha Berry",
"やすらぎのすず":"Soothe Bell",
"ヤタピのみ":"Petaya Berry",
"ヤチェのみ":"Yache Berry",
"ヤドランナイト":"Slowbronite",
"ヤミラミナイト":"Sablenite",
"やわらかいすな":"Soft Sand",
"ゆきだま":"Snowball",
"ユキノオナイト":"Abomasite",
"ようせいのハネ":"Fairy Feather",
"ヨプのみ":"Chople Berry",
"ヨロギのみ":"Charti Berry",
"ライボルトナイト":"Manectite",
"ラグラージナイト":"Swampertite",
"ラッキーパンチ":"Lucky Punch",
"ラティアスナイト":"Latiasite",
"ラティオスナイト":"Latiosite",
"ラムのみ":"Lum Berry",
"リザードナイトX":"Charizardite X",
"リザードナイトY":"Charizardite Y",
"りゅうのウロコ":"Dragon Scale",
"りゅうのキバ":"Dragon Fang",
"りゅうのプレート":"Draco Plate",
"リュガのみ":"Ganlon Berry",
"リリバのみ":"Babiri Berry",
"リンドのみ":"Rindo Berry",
"ルームサービス":"Room Service",
"ルカリオナイト":"Lucarionite",
"ルガルガンZ":"Lycanium Z",
"ルナアーラZ":"Lunalium Z",
"れいかいのぬの":"Reaper Cloth",
"レッドカード":"Red Card",
"レンブのみ":"Rowap Berry",
"ロゼルのみ":"Roseli Berry",
"ロックメモリ":"Rock Memory",
},
"nature": {
"いじっぱり":"Adamant",
"うっかりや":"Rash",
"おくびょう":"Timid",
"おだやか":"Calm",
"おっとり":"Mild",
"おとなしい":"Gentle",
"がんばりや":"Hardy",
"きまぐれ":"Quirky",
"さみしがり":"Lonely",
"しんちょう":"Careful",
"すなお":"Docile",
"ずぶとい":"Bold",
"せっかち":"Hasty",
"てれや":"Bashful",
"なまいき":"Sassy",
"のうてんき":"Lax",
"のんき":"Relaxed",
"ひかえめ":"Modest",
"まじめ":"Serious",
"むじゃき":"Naive",
"やんちゃ":"Naughty",
"ゆうかん":"Brave",
"ようき":"Jolly",
"れいせい":"Quiet",
"わんぱく":"Impish",
},
"type": {
"ノーマル": "Normal",
"ほのお": "Fire",
"みず": "Water",
"くさ": "Grass",
"でんき": "Electric",
"こおり": "Ice",
"かくとう": "Fighting",
"どく": "Poison",
"じめん": "Ground",
"ひこう": "Flying",
"エスパー": "Psychic",
"むし": "Bug",
"いわ": "Rock",
"ゴースト": "Ghost",
"ドラゴン": "Dragon",
"あく": "Dark",
"はがね": "Steel",
"フェアリー": "Fairy",
"ステラ": "Stellar"
}
}